BJS2-16031: Analytics request
CorporationX/analytics_service pull request #124
Opened 2024-08-06 19:11 UTC by malkov34

2024-08-11 01:19 UTC, pablo023 requested changes
В целом норм, но есть моменты, которые можно сделать лучше как по коду, так и по перформансу.

2024-08-11 01:19 UTC, pablo023 commented on src/main/java/faang/school/analytics/controller/AnalyticController.java
> +                                                @DateTimeFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss") LocalDateTime to) {
Как-то это так себе. Давай создадим какое-то дто, где все эти поля будут? Или запихнем их в AnalyticsEventDto. Хотя я бы сдеал отдельное дто тут, для интевала.

2024-08-11 01:19 UTC, pablo023 commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +    }
На аналитике данных может быть очень много, и этот фетч и сортировка в условиях высокой нагрузки, могут сильно просаживать производительность нашего сервиса. Лучше это выносить на уровень БД, и заниматься оптимизацией её перформанса, когда его перестанет хватать.

2024-08-11 01:19 UTC, pablo023 commented on src/test/java/faang/school/analytics/AnalyticsEventServiceTest.java
Ознакомься с аннотацией DisplayName

2024-08-12 12:37 UTC, malkov34 commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +    }
> На аналитике данных может быть очень много, и этот фетч и сортировка в условиях высокой нагрузки, могут сильно просаживать производительность нашего сервиса. Лучше это выносить на уровень БД, и заниматься оптимизацией её перформанса, когда его перестанет хватать.

Согласен, что на уровень бд выносить надо, чтобы лишнее не тянуть. Но в услових задачи был этот метод указан, поэтому его и использовал)

2024-08-12 22:48 UTC, merged