BJS2-25764
CorporationX/analytics_service pull request #140
Opened 2024-08-11 17:06 UTC by Caveri95

- Создан метод, который достает из БД все объекты AnalyticsEvent с данным receiverId и eventType, сортирует их по новшеству. Работает как с параметром Interval, так и просто с промежетком по дате
- Добавлен обработчик ошибок
- Написаны тесты

2024-08-19 05:09 UTC, pablo023 requested changes
Вынеси логику фильтрации в логику запроса к БД на репозиторном слое, чтобы мощностями БД это делать, а не сервисом.

2024-08-19 05:09 UTC, pablo023 commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +    }
Эту фильтрацию легче и проще описать на уровне запроса к БД.

2024-08-19 05:09 UTC, pablo023 commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +                                               LocalDateTime to) {
Это лучше собрать в дто

2024-08-19 05:46 UTC, Caveri95 commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +                                               LocalDateTime to) {
да, хорошо

2024-08-19 05:47 UTC, Caveri95 commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +    }
окей, сделаю метод в репозитории

2024-08-19 06:27 UTC, Caveri95 commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +    }
если мы используем готовый метод из репозитория, который возвращает нам уже стрим из данных по id и eventType, то эти методы (фильтрации на уровне репозитория) я не смогу использовать на репозитории. Мне нужно работать с готовым стримом, поэтому сделал в коде именно обработку
![image](https://github.com/user-attachments/assets/31ec018b-8ad6-46c3-9f39-62b19b066459)

2024-08-20 23:10 UTC, pablo023 commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +    }
Я имел ввиду написать вообще кастомную кверю и метод в репозитории. Если хочешь - попробуй сделать, было бы интересно, если нет - можешь мержить, и кидать в done

2024-08-21 17:14 UTC, merged