Запрос аналитики Никита
CorporationX/analytics_service pull request #142
Opened 2024-08-12 11:32 UTC by kpzxpf

2024-08-19 04:52 UTC, pablo023 requested changes
Ты по моему слой API тут забыл?

2024-08-19 04:52 UTC, pablo023 commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +            long receiverId, EventType eventType, Interval interval, LocalDateTime from, LocalDateTime to) {
Давай может это в дто оформим?

2024-08-19 04:52 UTC, pablo023 commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +                .sorted(Comparator.comparing(AnalyticsEvent::getReceivedAt))
Давай это на сторону запроса к БД перенесем, в виде квери на репозиторном слое?

2024-08-19 04:52 UTC, pablo023 commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +            }
Эта логика фильтрации должна быть реализована через интерфейс фильтрующий, и список его реализаций, как мы делали это в начале проекта.

2024-08-20 19:12 UTC, kpzxpf commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +            long receiverId, EventType eventType, Interval interval, LocalDateTime from, LocalDateTime to) {
хорошо

2024-08-20 19:12 UTC, kpzxpf commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +                .sorted(Comparator.comparing(AnalyticsEvent::getReceivedAt))
ок

2024-08-20 19:12 UTC, kpzxpf commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +            }
ок

2024-08-20 22:35 UTC, merged