BJS2-25779
CorporationX/analytics_service pull request #145
Opened 2024-08-12 19:03 UTC by Caveri95

- Добавлен эндпоинт на получение AnalyticsEvent по receiverId и временному диапазону

2024-08-19 05:13 UTC, pablo023 requested changes

2024-08-19 05:13 UTC, pablo023 commented on src/main/java/faang/school/analytics/controller/AnalyticsEventController.java
> +                                               @RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) LocalDateTime to) {
Почему бы не сделать это дто? Как-то много параметров как будто, сложно выглядит, читается не очень

2024-08-19 05:13 UTC, pablo023 commented on src/test/resources/db/data.sql
Это видимо тестовые данные, которые случайно сюда попали

2024-08-19 05:13 UTC, pablo023 commented on src/test/resources/application.yaml
> +        followerView: follower_view_channel
Похоже на часть функционала из другой задачи, здесь это должно быть?

2024-08-19 05:13 UTC, pablo023 commented on src/test/resources/db/schema.sql
А зачем нам эти эвенты в базе сторить? Объясни, пожалуйста.

2024-08-20 17:19 UTC, Caveri95 commented on src/main/java/faang/school/analytics/controller/AnalyticsEventController.java
> +                                               @RequestParam(required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) LocalDateTime to) {
Да, хорошо

2024-08-20 18:04 UTC, Caveri95 commented on src/test/resources/db/data.sql
Это данные для заполнения БД для тестов. Использовал тестовую БД для тестов контроллера

2024-08-20 18:05 UTC, Caveri95 commented on src/test/resources/db/schema.sql
Туда же к тестовым данным для тестов контроллеров

2024-08-20 18:05 UTC, Caveri95 commented on src/test/resources/application.yaml
> +        followerView: follower_view_channel
У меня PR получается в другую мою задачу, а там нужно было конфиг Redis делать, поэтому это здесь

2024-08-20 22:44 UTC, pablo023 commented
Пофикси конфликты, и можешь мержить, и кидать в done

2024-08-21 17:12 UTC, merged