BJS2-15660
CorporationX/analytics_service pull request #151
Opened 2024-08-15 06:56 UTC by YPG0

Сбор аналитики для лайков постов через LikeEventListener

2024-08-16 21:13 UTC, ravshanbekn commented on src/main/java/faang/school/analytics/config/LikeListenerConfig.java
> +    public ChannelTopic nameTopic() {
Название метода пойдет как название бина, а название метода не совсем подходящее

2024-08-16 21:20 UTC, ravshanbekn commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +    }
А если для еще одного Event тоже понадобится такой же функционал, нужно будет реализовывать новый метод с почти таким же функционалом, но другим названием?

2024-08-16 21:23 UTC, ravshanbekn reviewed
Нормально выглядит

2024-08-19 17:37 UTC, YPG0 commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +    }
Согласен переделал

2024-08-25 01:16 UTC, pablo023 requested changes

2024-08-25 01:16 UTC, pablo023 commented on src/main/java/faang/school/analytics/config/LikeListenerConfig.java
> +    public ChannelTopic likeTopicName() {
likeTopicChannel

2024-08-25 01:16 UTC, pablo023 commented on src/main/java/faang/school/analytics/config/LikeListenerConfig.java
> +    }
Почему у тебя бин redisContainer привязан эксклюзивно к топику лайков?

2024-08-25 01:16 UTC, pablo023 commented on src/main/java/faang/school/analytics/mapper/AnalyticsEventMapper.java
Так себе, конечно. Учись пользоваться мапстрактом, он для этого как раз существует.

2024-08-25 01:16 UTC, pablo023 commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +            throw new RuntimeException(e);
Так нельзя. Нужно кидать осмысленные эксепшены, которые описывают суть того, что тут, где, и на каких данных не так пошло, чтобы было проще дебажить.

2024-08-25 01:31 UTC, pablo023 commented
В целом, тут косметика. Можешь конфликты исправить, и вот этот вмержить.

2024-08-26 08:05 UTC, YPG0 commented on src/main/java/faang/school/analytics/config/LikeListenerConfig.java
> +    public ChannelTopic likeTopicName() {
+

2024-08-27 16:31 UTC, YPG0 commented on src/main/java/faang/school/analytics/mapper/AnalyticsEventMapper.java
Сделал мапстрактом

2024-08-27 16:32 UTC, YPG0 commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +            throw new RuntimeException(e);
Вроде поправил

2024-08-30 22:47 UTC, merged