BJS2-15653 Profile View Event
CorporationX/analytics_service pull request #164
Opened 2024-08-21 11:32 UTC by GevorgSogomonian

Added RedisConfig
Added ProfileViewEvent
Added RedisMessageSubscriber
Added ProfileViewEventMapper
Added AnalyticsEventService

2024-08-28 03:41 UTC, pablo023 requested changes
Тут только косметика, но раз нам не на чем в рамках ПР сфокусироваться на ревью - исправь её хотя бы. Тоже важно

2024-08-28 03:41 UTC, pablo023 commented on src/main/java/faang/school/analytics/config/RedisConfig.java
> +    @Autowired
Лучше не использовать Autowired

https://www.baeldung.com/java-spring-field-injection-cons

2024-08-28 03:41 UTC, pablo023 commented on src/main/java/faang/school/analytics/config/RedisConfig.java
> +    ChannelTopic userViewTopic() {
Почему тут не указал модификаторы доступа?

2024-08-28 03:41 UTC, pablo023 commented on src/main/java/faang/school/analytics/dto/ProfileViewEvent.java
> +@Data
Зачем тебе дата тут?

2024-08-28 03:41 UTC, pablo023 commented on src/main/java/faang/school/analytics/listener/RedisMessageSubscriber.java
> +            throw new RuntimeException(e);
Когда ты обрабатываешь исключение, добавляй инфы - иначе оно просто кидается, нууу и что? Непонятно - что, где случилось, на каких данных. Нужно писать сообщение, которое поможет разобраться в ошибке быстро - где, и почему она произошла

2024-09-01 07:22 UTC, GevorgSogomonian commented on src/main/java/faang/school/analytics/config/RedisConfig.java
> +    @Autowired
исправил

2024-09-01 07:23 UTC, GevorgSogomonian commented on src/main/java/faang/school/analytics/config/RedisConfig.java
> +    ChannelTopic userViewTopic() {
исправил

2024-09-01 07:24 UTC, GevorgSogomonian commented on src/main/java/faang/school/analytics/dto/ProfileViewEvent.java
> +@Data
Согласен, можно убрать

2024-09-01 07:42 UTC, GevorgSogomonian commented on src/main/java/faang/school/analytics/listener/RedisMessageSubscriber.java
> +            throw new RuntimeException(e);
исправил

2024-09-03 14:55 UTC, merged