BJS2-27094 Сохранение и получение аналитики
CorporationX/analytics_service pull request #181
Opened 2024-10-07 13:45 UTC by ilu23ilu23

Создан сервисный класс AnalyticsEventService с тестами и класс, описывающий интервалы Interval

2024-10-08 01:01 UTC, amilosh commented on src/main/java/faang/school/analytics/model/Interval.java
> +    YEAR_TO_DATE (LocalDateTime.of(LocalDate.now().getYear(),1,1,0,0), LocalDateTime.now());
Если сделать ctrl+alt+L то идея скобочки приклеивает к енамам

2024-10-08 01:01 UTC, amilosh commented on src/main/java/faang/school/analytics/model/Interval.java
> +
можно убрать

2024-10-08 01:01 UTC, amilosh commented on src/main/java/faang/school/analytics/model/Interval.java
> +    LAST_DAY (LocalDateTime.of(LocalDate.now().minusDays(1), LocalTime.MIN), LocalDateTime.now()),
А эти значения LocalDate.now() и LocalDateTime.now()
они каждый раз будут с новым значением при обращении к Interval.LAST_DAY

или один раз проинициализируются в самом начале и остантся авсегда?

2024-10-08 01:01 UTC, amilosh commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +
лишняя

2024-10-08 01:01 UTC, amilosh commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +            return eventStream.collect(Collectors.toList());
Этот Stream - он AutoCloseable. Его не надо в трай с ресурсами брать. (только Closeable надо брать.

2024-10-08 01:01 UTC, amilosh commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +            return eventStream.collect(Collectors.toList());
Ещё Дима в предыдущих ревьюях говорил, чтобы в репозитории мы меняли с CrudRepository на JpaRepository и возвращали List<AnalyticsEvent>
А Stream уже создавали в сервисе.

2024-10-08 01:01 UTC, amilosh commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +        }
Можно создать утильный класс типа DateUtils с методом
boolean isBetweenInclusive(Date date, Date from, Date to)

2024-10-08 01:01 UTC, amilosh commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +                .collect(Collectors.toList());
просто .toList(); можно

2024-10-08 01:02 UTC, amilosh commented on src/main/java/faang/school/analytics/model/Interval.java
> +
пустую строку

2024-10-08 10:05 UTC, sultan-inked reviewed
👀

2024-10-08 12:12 UTC, ilu23ilu23 commented on src/main/java/faang/school/analytics/model/Interval.java
> +    LAST_DAY (LocalDateTime.of(LocalDate.now().minusDays(1), LocalTime.MIN), LocalDateTime.now()),
Да, один раз проинициализируются и останутся, переделаю

2024-10-08 17:38 UTC, ilu23ilu23 commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +            return eventStream.collect(Collectors.toList());
Да, так даже легче

2024-10-10 13:42 UTC, 20cognosce requested changes

2024-10-10 13:42 UTC, 20cognosce commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +    }
Из топика евент приходит

2024-10-10 13:42 UTC, 20cognosce commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +    }
![image](https://github.com/user-attachments/assets/8ebb3448-1665-4aec-b1f9-dd01e371d93c)

2024-10-10 13:42 UTC, 20cognosce commented on src/main/java/faang/school/analytics/model/Interval.java
> +    }
Можно пожалуйста убрать логику из енама, это шляпа
В сервисе определи, какой енам какие границы задаёт

2024-10-11 16:07 UTC, 20cognosce approved these changes

2024-10-11 16:07 UTC, merged