BJS2-27099   Запрос аналитики
CorporationX/analytics_service pull request #182
Opened 2024-10-07 13:50 UTC by ilu23ilu23

Продолжение задачи [BJS2-27094] Сохранение и получение аналитики

Тут контроллер с сервисным классом для обработки входящих значений и валидации

2024-10-08 01:29 UTC, amilosh commented on src/main/java/faang/school/analytics/dto/analyticsEvent/AnalyticsEventDto.java
> +@Builder
я вот так форматирую

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor

2024-10-08 01:29 UTC, amilosh commented on src/main/java/faang/school/analytics/service/AnalyticsRequestService.java
> +            int index = Integer.parseInt(eventType);
какие-то свистопляски в условии)

2024-10-08 01:29 UTC, amilosh commented on src/main/java/faang/school/analytics/dto/analyticsEvent/AnalyticsEventDto.java
> +    private long receiverId;
тут кстати примитив, нал нельзя засетать
@NotNull(message = "Receiver ID cannot be null") даже не обязателен, но пусть будет, с ним красивее

2024-10-08 01:29 UTC, amilosh commented on src/main/java/faang/school/analytics/exception/GlobalExceptionHandler.java
> +    public ResponseEntity<String> handleAnalyticsRequestException(AnalyticsException ex) {
handleAnalyticsException

2024-10-08 01:29 UTC, amilosh commented on src/main/java/faang/school/analytics/service/AnalyticsRequestService.java
> +    private static final DateTimeFormatter DATE_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss");
можно даже в константы вынести
чобы в любом месте прилаги заиспользовать

"yyyy-MM-dd'T'HH:mm:ss" - это тоже как стринг константа

2024-10-08 01:29 UTC, amilosh commented on src/main/java/faang/school/analytics/service/AnalyticsRequestService.java
> +            throw new InvalidDateException("Invalid date format. Expected format: yyyy-MM-dd'T'HH:mm:ss");
и тогда ту константу (yyyy-MM-dd'T'HH:mm:ss) сюда

2024-10-08 11:42 UTC, ilu23ilu23 commented on src/main/java/faang/school/analytics/service/AnalyticsRequestService.java
> +            int index = Integer.parseInt(eventType);
Да, там и так и сяк по требованиям)

2024-10-10 13:24 UTC, 20cognosce requested changes

2024-10-10 13:24 UTC, 20cognosce commented on src/main/java/faang/school/analytics/controller/AnalyticsEventController.java
> +    }
Что ты сохраняешь?
События из брокера приходят, не по ресту

2024-10-10 13:24 UTC, 20cognosce commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +    }
События приходят из редиса

2024-10-10 13:24 UTC, 20cognosce commented on src/main/java/faang/school/analytics/model/Interval.java
> +    YEAR_TO_DATE (LocalDateTime.of(LocalDate.now().getYear(),1,1,0,0), LocalDateTime.now());
Тебя не смущает, что даты создадутся один раз при старте приложения
И условно через час from и to устареют

2024-10-10 13:24 UTC, 20cognosce commented on src/main/java/faang/school/analytics/model/Interval.java
> +    YEAR_TO_DATE (LocalDateTime.of(LocalDate.now().getYear(),1,1,0,0), LocalDateTime.now());
И твои запросы будут по кривым интервалам

2024-10-10 13:24 UTC, 20cognosce commented on src/main/java/faang/school/analytics/service/AnalyticsRequestService.java
> +            return EventType.values()[index];
Это не нормально по индексу доставать енам

2024-10-10 13:24 UTC, 20cognosce commented on src/main/java/faang/school/analytics/service/AnalyticsRequestService.java
> +            return Interval.values()[index];
Нет

2024-10-10 13:24 UTC, 20cognosce commented on src/main/java/faang/school/analytics/service/AnalyticsRequestService.java
> +        LocalDateTime toDateTime = (to != null) ? convertToLocalDateTime(to) : null;
А можно не null туда-сюда перекидывать в ожидании NPE, а задать дефолтные значения?

from - epoch date
to -  now()
interval - за всё время

взаимоисключения тоже проработать

2024-10-10 13:24 UTC, 20cognosce commented on src/main/java/faang/school/analytics/service/AnalyticsRequestService.java
> +        Interval intervalEnum = (interval != null) ? convertToInterval(interval) : null;
Почему метод, от которого зависит processRequestParams находите выше в классе

Те, у кого меньше зависимостей - вниз, ближе к приватным методам

2024-10-10 14:18 UTC, ilu23ilu23 commented on src/main/java/faang/school/analytics/model/Interval.java
> +    YEAR_TO_DATE (LocalDateTime.of(LocalDate.now().getYear(),1,1,0,0), LocalDateTime.now());
Это я поправил в пул реквесте 27094, тут не обновил

2024-10-10 14:19 UTC, ilu23ilu23 commented on src/main/java/faang/school/analytics/service/AnalyticsRequestService.java
> +            return EventType.values()[index];
Согласен, но это было по условию, поэтому и сделал

2024-10-10 14:19 UTC, ilu23ilu23 commented on src/main/java/faang/school/analytics/service/AnalyticsRequestService.java
> +            return Interval.values()[index];
В условии так было

2024-10-11 16:12 UTC, 20cognosce requested changes

2024-10-11 16:12 UTC, 20cognosce commented on src/main/java/faang/school/analytics/controller/AnalyticsEventController.java
> +            @RequestParam(required = false) String to) {
```
getAnalytics(@RequestParam long receiverId,
             @RequestParam String eventType,
```

2024-10-11 16:12 UTC, 20cognosce commented on src/main/java/faang/school/analytics/controller/AnalyticsEventController.java
> +    @GetMapping("/get-analytics-event")
/event
мы итак на subpath /analytics находим
это итак get запрос

2024-10-11 16:12 UTC, 20cognosce commented on src/main/java/faang/school/analytics/model/Interval.java
> +    private final LocalDateTime to;
Это неправильно

2024-10-11 16:12 UTC, 20cognosce commented on src/main/java/faang/school/analytics/model/Interval.java
> +    private final LocalDateTime to;
Возьми из второй задачи

2024-10-11 16:12 UTC, 20cognosce commented on src/main/java/faang/school/analytics/service/AnalyticsRequestService.java
> +            return Interval.values()[index];
Убери число, оставь только Enum, нафиг такое условие

2024-10-14 20:16 UTC, 20cognosce approved these changes

2024-10-14 20:16 UTC, 20cognosce commented on src/main/java/faang/school/analytics/service/AnalyticsRequestService.java
> +                    : LocalDateTime.now();
100500 проверок на null, у меня глаз дергается
Ну нельзя более элегантно это обдумать

2024-10-14 20:16 UTC, 20cognosce commented on src/main/java/faang/school/analytics/service/AnalyticsRequestService.java
> +                throw new IllegalArgumentException("Нельзя указывать 'from' или 'to', когда задан 'interval'.");
\

2024-10-14 20:17 UTC, merged