BJS2-29112 добавлен ci/cd and checkstyle
CorporationX/analytics_service pull request #184
Opened 2024-10-07 21:07 UTC by KarabbasBarabas

2024-10-08 19:19 UTC, mysosnovskaya requested changes
Не вижу, чтобы проверка в гитхабе запускалась. Т.е. сейчас что-то не то, нужно разобраться. Иначе я не смогу убедиться, что ты всё верно настроил)

2024-10-08 19:19 UTC, mysosnovskaya commented on src/test/java/faang/school/analytics/service/TestClassTest.java
> +public class TestClassTest {
А зачем эти тесты? Это для jacoco нужно? Просто потом можно забыть удалить и такое останется в проекте)

2024-10-09 19:44 UTC, KarabbasBarabas commented
так а сейчас этих файлов ещё нет в нашей мастер ветки, а триггер в GitHub actions настроен на пуш и пулл реквест в нашу мастер ветку

2024-10-09 19:45 UTC, KarabbasBarabas commented on src/test/java/faang/school/analytics/service/TestClassTest.java
> +public class TestClassTest {
это да, я тестировал на них

2024-10-09 19:46 UTC, KarabbasBarabas commented
вот тут запускал 
https://github.com/CorporationX/analytics_service/actions/runs/11223778573

2024-10-10 19:32 UTC, mysosnovskaya commented
> так а сейчас этих файлов ещё нет в нашей мастер ветки, а триггер в GitHub actions настроен на пуш и пул реквест в нашу мастер ветку

Странно, у Максима почему-то запускалось. Это же ПР в мастер-ветку. Ну давай попробую смержить, посмотрим)

2024-10-10 19:32 UTC, mysosnovskaya approved these changes

2024-10-10 19:32 UTC, merged