Feature bjs2 26152
CorporationX/analytics_service pull request #185
Opened 2024-10-08 12:58 UTC by Silencemess1ah

- Added service + base controller
- Interval enum
- Swagger integration
- Base logic from task + test on service

2024-10-08 20:06 UTC, GusevVrn reviewed
Вообще по хорошему разбить задачи, swagger и остальное. Т.к. в кучу все намешано

2024-10-08 20:06 UTC, GusevVrn commented on src/main/java/faang/school/analytics/model/Interval.java
> +
задумку понял, но почему в дто сразу enum не принимать? 
хочешь интервал от- заполняешь одну дату ОТ и он тебе возвращает с указанного по текущее число
хочешь интервал - заполняешь ожидаемыми значениями, нет - получи ошибку.

2024-10-08 20:06 UTC, GusevVrn commented on src/main/java/faang/school/analytics/model/Interval.java
> +        String unit = parts[1].toUpperCase();
а если я передал "1", на сцену выйдет outOfBound?

2024-10-08 20:06 UTC, GusevVrn commented on src/main/java/faang/school/analytics/service/analytics_event/AnalyticsEventService.java
> +        AnalyticsEventDto savedDto = analyticsEventMapper.toDto(analyticsEventRepository.save(analyticsEvent));
вынеси save, я не сразу понял почему savedDto

2024-10-08 20:06 UTC, GusevVrn commented on src/main/java/faang/school/analytics/controller/analytics_event/AnalyticsEventController.java
> +@Validated
чисто для красоты, validated в самый верх, чтоб лесенка была))

2024-10-08 20:06 UTC, GusevVrn commented on src/main/java/faang/school/analytics/service/analytics_event/AnalyticsEventService.java
> +            LocalDateTime to = analyticsEventGetDto.getTo();
я бы предположил что может быть случай, когда TO не заполнен и тогда делать по currentTimeStamp

2024-10-08 20:31 UTC, Silencemess1ah commented on src/main/java/faang/school/analytics/model/Interval.java
> +
Не знаю меня запутало описание на платформе сказано что можно мол строку или число вообще что угодно передать я поэтому и решил что просто пишут 5 days , 1 month 3 years и т.д. и отсюда отталкивался, проще конечно удалить этот интервал и просто дату с которой найти да и всё...

2024-10-08 20:38 UTC, Silencemess1ah commented on src/main/java/faang/school/analytics/model/Interval.java
> +
Честно блин вроде задача о другом, а пол дня убил на этот интервал как и что сделать, обидно и могу понять как будет оптимальнее... В общем чтобы не застрять опять на пол дня кину как есть ниже только твой коммент учту про сцену и веселый аутОфБаундс, может Маша что предложит как это обработать чтоб все варианты учесть

2024-10-08 20:38 UTC, Silencemess1ah commented on src/main/java/faang/school/analytics/model/Interval.java
> +        String unit = parts[1].toUpperCase();
Именно он, поправил с проверкой что партс > 1

2024-10-08 21:24 UTC, mysosnovskaya requested changes

2024-10-08 21:24 UTC, mysosnovskaya commented on src/main/java/faang/school/analytics/model/Interval.java
> +
Можно сделать заранее заданные интервалы, типа 1_WEEK, 3_MONTHS. Так и в реализации будет проще, и требование будет выполнено. Но если отойти от требований, то тогда:
1. Либо действительно вообще убирать интервал и пользоваться только to
2. Либо принимать int (количество) и interval (enum - day, hour, week).
Я либо за второй вариант (с двумя параметрами, он более гибкий и удобный), либо за самый первый с заранее заданными интервалами (менее гибкий, но под требования). Можешь выбрать самостоятельно, я приму любой вариант

2024-10-08 21:24 UTC, mysosnovskaya commented on src/main/java/faang/school/analytics/dto/analytics_event/AnalyticsEventGetDto.java
> +    @Schema(description = "Interval from which you need analytics to present (can be null if from and to provided)",
Перед аннотациями лучше пустые строчки оставить, а то в гитхабе всё сливается в один бесконечный код)

2024-10-08 21:24 UTC, mysosnovskaya commented on src/main/java/faang/school/analytics/exception/IntervalsNotValidException.java
> +public class IntervalsNotValidException extends RuntimeException{
Стиль не соблюден, нужно поправить (пробелов не хватает)

2024-10-08 21:24 UTC, mysosnovskaya commented on src/main/java/faang/school/analytics/mapper/analytics_event/AnalyticsEventMapper.java
> +    AnalyticsEventDto toDto(AnalyticsEvent analyticsEvent);
Лучше назвать toAnalyticsEventDto, а то могут и другие dto появиться

2024-10-08 21:24 UTC, mysosnovskaya commented on src/main/java/faang/school/analytics/service/analytics_event/AnalyticsEventService.java
> +            return analyticsEventRepository.findByReceiverIdAndEventType(receiverId, eventType)
Тут дублирование присутствует с предыдущим блоком. Подумай, как от него избавиться) По сути разница только в filter

2024-10-09 21:41 UTC, mysosnovskaya requested changes

2024-10-09 21:41 UTC, mysosnovskaya commented on src/main/java/faang/school/analytics/model/TimeUnit.java
> +            log.warn("No interval value was found for {}", timeUnit);
А я бы ошибку сгенерировала. Иначе если вернется null, то мы получим NPE там, где вызывали метод startDate

2024-10-09 21:41 UTC, mysosnovskaya commented on src/main/java/faang/school/analytics/model/TimeUnit.java
> +    public static LocalDateTime startDate(int quantity, TimeUnit timeUnit) {
Метод нужно переименовать, чтобы был глаголом

2024-10-09 21:41 UTC, mysosnovskaya commented on src/main/java/faang/school/analytics/service/analytics_event/AnalyticsEventService.java
> +                    if (timeUnit != null && timeQuantity != null) {
Давай вынесем эту логику в отдельный приватный метод с понятным названием. По сути здесь возвращается фильтр

2024-10-11 19:17 UTC, mysosnovskaya approved these changes

2024-10-11 19:17 UTC, merged