Анализ посещаемости профиля пользователя BJS2-27088
CorporationX/analytics_service pull request #188
Opened 2024-10-08 14:54 UTC by sultan-inked

2024-10-11 08:51 UTC, sultan-inked commented
Мне не нравиться реализация сохранения, хочу переделать. 
Сейчас в случае сбоя сохранения данные потеряются, не делей пока ревью

2024-10-11 12:24 UTC, sultan-inked commented
Исправил, теперь если при сохранении дынных будет сбой, то ничего не потеряется и будет повторная попытка позже

2024-10-11 23:56 UTC, amilosh commented on logs/user_service.log
> +19:11:42.577 [background-preinit] INFO  o.h.validator.internal.util.Version - HV000001: Hibernate Validator 8.0.0.Final
Специально добавил или по-ошибке?

2024-10-11 23:56 UTC, amilosh commented on src/main/java/faang/school/analytics/AnalyticsServiceApp.java
> +
всё-таки давай слитно, что однообразно во всем проекте

2024-10-11 23:56 UTC, amilosh commented on src/main/java/faang/school/analytics/config/redis/user/UserRedisListenerConfig.java
> +    @Qualifier("profileViewEventListener")
такие же мысли как в user_service
если там проканает, то и тут так сделай

2024-10-11 23:56 UTC, amilosh commented on src/main/java/faang/school/analytics/mapper/AnalyticsEventMapper.java
> +
а я всё до срточек докапываюсь)

2024-10-11 23:56 UTC, amilosh commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +        return analyticsEventRepository.saveAll(events);
Выглядит так, что 
actorId - это тот кто совершил действие, то есть viewer
receiverId - тот, над ком совершилось действие

2024-10-11 23:56 UTC, amilosh commented on src/main/java/faang/school/analytics/service/user/listener/RedisProfileViewEventSubscriber.java
> +            analyticsEvents.add(analyticsEvent);
Здесь если удастся принять лист, то не придётся с List<AnalyticsEvent> analyticsEvents изголяться

2024-10-11 23:56 UTC, amilosh commented on src/main/resources/logback.xml
> +
этот файл можешь удалить
logback-spring на себя всё берет

2024-10-12 06:11 UTC, sultan-inked commented on logs/user_service.log
> +19:11:42.577 [background-preinit] INFO  o.h.validator.internal.util.Version - HV000001: Hibernate Validator 8.0.0.Final
Незнаю что это, и почему добавилось

2024-10-12 06:12 UTC, sultan-inked commented on src/main/java/faang/school/analytics/AnalyticsServiceApp.java
> +
Нет, методы я лепить не буду, мы же их друг у другу не лепим, мы же договорились переменные лепить

2024-10-12 06:24 UTC, sultan-inked commented on src/main/java/faang/school/analytics/AnalyticsServiceApp.java
> +
Хотя ладно, тоже буду лепить)

2024-10-12 06:47 UTC, sultan-inked commented on src/main/java/faang/school/analytics/config/redis/user/UserRedisListenerConfig.java
> +    @Qualifier("profileViewEventListener")
Да, спасибо, не знал

2024-10-12 08:11 UTC, sultan-inked commented on src/main/java/faang/school/analytics/mapper/AnalyticsEventMapper.java
> +
Убрал

2024-10-12 08:15 UTC, sultan-inked commented on src/main/resources/logback.xml
> +
Я его скопировал с другого сервиса, где цветные логи, что бы и здесь так же было, или я не правильно понял как настроить, куда то еще можно записать?

2024-10-12 08:17 UTC, sultan-inked commented on src/main/java/faang/school/analytics/service/user/listener/RedisProfileViewEventSubscriber.java
> +            analyticsEvents.add(analyticsEvent);
С List analyticsEvents придется изголяться, что бы в случае ошибки сохранения в бд, не потерять данные

2024-10-12 08:17 UTC, sultan-inked commented on src/main/java/faang/school/analytics/service/user/listener/RedisProfileViewEventSubscriber.java
> +            analyticsEvents.add(analyticsEvent);
Или есть другой способ?

2024-10-12 10:17 UTC, sultan-inked commented on src/main/java/faang/school/analytics/service/user/listener/RedisProfileViewEventSubscriber.java
> +            analyticsEvents.add(analyticsEvent);
Переделал, теперь передаю лист

2024-10-14 20:35 UTC, 20cognosce requested changes

2024-10-14 20:35 UTC, 20cognosce commented on src/main/java/faang/school/analytics/config/scheduler/user/UserViewEventSaveQuartzConfig.java
> +public class UserViewEventSaveQuartzConfig {
Это что, тут тебе джоба зачем? Ты срабатываешь на ивент, какой скедулер?

2024-10-14 20:35 UTC, 20cognosce commented on src/main/java/faang/school/analytics/config/redis/user/UserRedisListenerConfig.java
> +public class UserRedisListenerConfig {
Так есть же уже?
В готовый добавь только свой топик

2024-10-14 20:35 UTC, 20cognosce commented on src/main/java/faang/school/analytics/config/redis/RedisConfig.java
> +public class RedisConfig {
Ты уверен, что в сервисе аналитики это еще не настроено

2024-10-14 20:35 UTC, 20cognosce commented on src/main/java/faang/school/analytics/service/listener/RedisEventSubscriberBatchSave.java
> +public abstract class RedisEventSubscriberBatchSave<T> implements MessageListener {
Ой всё
У кого в руках молоток, тому везде мерещутся гвозди

2024-10-14 20:35 UTC, 20cognosce commented on src/main/java/faang/school/analytics/service/listener/RedisEventSubscriberBatchSave.java
> +public abstract class RedisEventSubscriberBatchSave<T> implements MessageListener {
Убирай батчи и всё это безобразие
Пришел ивент - сразу его обработал и сохранил, хватит накручивал космолёты

2024-10-14 20:35 UTC, 20cognosce commented on src/main/java/faang/school/analytics/service/user/job/UserViewEventSaveJob.java
> +public class UserViewEventSaveJob implements Job {
Удалить

2024-10-14 20:35 UTC, 20cognosce commented on src/main/java/faang/school/analytics/service/user/listener/RedisProfileViewEventSubscriber.java
> +    }
onMessage {
repo.save()
}

всёёёёёёёёё

2024-10-16 12:28 UTC, sultan-inked commented on src/main/resources/logback.xml
> +
Удалил

2024-10-16 12:56 UTC, sultan-inked commented on src/main/java/faang/school/analytics/config/redis/RedisConfig.java
> +public class RedisConfig {
Я не нашел конфиг

2024-10-16 20:56 UTC, 20cognosce approved these changes

2024-10-16 20:56 UTC, merged