- listener and redisConfig v.1
CorporationX/analytics_service pull request #191
Opened 2024-10-08 20:19 UTC by Silencemess1ah

- Redis config
- listener

2024-10-15 20:13 UTC, GusevVrn reviewed
Если что, я postService сперва посмотрел.

В целом нормально, чуть конфиг поправить и по объету в redis подумать

2024-10-15 20:13 UTC, GusevVrn commented on src/main/java/faang/school/analytics/config/redis/RedisPropertiesConfiguration.java
> +    @Value("${spring.data.redis.channel.like-event}")
ну тут тоже от value бы избавиться

2024-10-15 20:13 UTC, GusevVrn commented on src/main/java/faang/school/analytics/config/redis/RedisConfiguration.java
> +        container.addMessageListener(likeEventListenerAdapter(likeEventsListener), likeEventsTopic());
тут что-то не так, тебе не нужен likeEventsListener вообще,
просто likeEventListenerAdapter должно пройти

2024-10-15 20:13 UTC, GusevVrn commented on src/main/java/faang/school/analytics/dto/event/like/LikeEventDto.java
> +@Data
опять дата(

2024-10-15 20:13 UTC, GusevVrn commented on src/main/java/faang/school/analytics/listener/like/LikeEventListener.java
> +        String jsonString = new String(message.getBody(), StandardCharsets.UTF_8).trim();
вот типо ты там объект колдуешь в стрингу, а тут наоборот,
лишние действия просто dto кидай и через маппер их правь

2024-10-16 08:29 UTC, Silencemess1ah commented on src/main/java/faang/school/analytics/listener/like/LikeEventListener.java
> +        String jsonString = new String(message.getBody(), StandardCharsets.UTF_8).trim();
Я так делаю потому что дичь прилетает либо вообще не сериализует либо криво, пришлось на 8ми костылях запиливать, щас делаю второй паб саб там попробую учесть твои комменты возможно заработает тогда здесь отрефачу

2024-10-18 15:43 UTC, mysosnovskaya requested changes

2024-10-18 15:43 UTC, mysosnovskaya commented on src/main/java/faang/school/analytics/config/redis/RedisConfiguration.java
> +    public RedisTemplate<String, Object> redisTemplate() {
А это зачем здесь?)

2024-10-18 15:43 UTC, mysosnovskaya commented on src/main/java/faang/school/analytics/config/redis/RedisProperties.java
> +        private String profile_view;
Аналогично - должен быть camelCase

2024-10-19 14:10 UTC, mysosnovskaya approved these changes

2024-10-20 21:28 UTC, merged