Сохранение и получение аналитики
CorporationX/analytics_service pull request #196
Opened 2024-10-09 17:15 UTC by RuslanIovlev

2024-10-10 05:46 UTC, SharkB38 approved these changes

2024-10-10 06:04 UTC, ArstanSubanov approved these changes
Вроде всё отлично)

2024-10-10 06:04 UTC, ArstanSubanov commented on src/main/java/faang/school/analytics/service/AnalyticsEventServiceImpl.java
> +        return !date.isBefore(from) && !date.isAfter(to);
Может наоборот сделать и убрать отрицание? date.isAfter(from) && date.isBefore(to)?

2024-10-11 19:14 UTC, mysosnovskaya requested changes

2024-10-11 19:14 UTC, mysosnovskaya commented on src/main/java/faang/school/analytics/dto/AnalyticsEventDto.java
> +public class AnalyticsEventDto {
Так а что решили с абстрактным классом, который Валера и Виталя предложили?

2024-10-11 19:14 UTC, mysosnovskaya commented on src/main/java/faang/school/analytics/service/AnalyticsEventServiceImpl.java
> +        return switch (interval) {
Классно, что такой новомодный switch используешь 👍

2024-10-11 19:14 UTC, mysosnovskaya commented on src/main/java/faang/school/analytics/service/AnalyticsEventServiceImpl.java
> +            case HOUR -> date.isAfter(now.minusHours(1));
Почему 1? Я тут вижу два решения: либо интервалы должны быть типа 3_MONTHS, 1_WEEK и так далее, либо в getAnalytics добавить ещё один параметр для интервала (количество). По условию задачи как будто бы нужен первый вариант)

2024-10-11 19:14 UTC, mysosnovskaya commented on src/main/java/faang/school/analytics/service/AnalyticsEventServiceImpl.java
> +        return analyticsEventStream.filter(event -> matchesIntervalOrPeriod(event.getReceivedAt(), interval, from, to))
Хорошо, что выделил метод matchesIntervalOrPeriod 👍

2024-10-13 15:26 UTC, RuslanIovlev commented on src/main/java/faang/school/analytics/dto/AnalyticsEventDto.java
> +public class AnalyticsEventDto {
Не знаю ребята ничего не писали

2024-10-13 15:28 UTC, SharkB38 commented on src/main/java/faang/school/analytics/dto/AnalyticsEventDto.java
> +public class AnalyticsEventDto {
Мы же на созвоне обсудили, чтобы сервис принимал AbstractEvent для сохранения

2024-10-13 17:08 UTC, RuslanIovlev commented on src/main/java/faang/school/analytics/dto/AnalyticsEventDto.java
> +public class AnalyticsEventDto {
Я на созвоне просто на работе еще был, поэтому не все услышал что конкретно хотели сделать, хорошо посмотрю

2024-10-15 19:01 UTC, RuslanIovlev commented on src/main/java/faang/school/analytics/service/AnalyticsEventServiceImpl.java
> +            case HOUR -> date.isAfter(now.minusHours(1));
А почему такие интервалы должны быть?
Я понял так что мы берем за интервал 1 день 1 месяц 1 год

2024-10-16 13:23 UTC, mysosnovskaya commented on src/main/java/faang/school/analytics/dto/AnalyticsEventDto.java
> +public class AnalyticsEventDto {
@RuslanIovlev по-хорошему, если ты не до конца понял, что от тебе предлагали, то нужно было позже к Валере или Виталей обратиться и уточнить. А то получилось так, что не понял и не сделал. На реальной работе так дело не пойдет) Это хорошо, что я была при этом разговоре и на ревью смогла вспомнить об этом.

2024-10-16 13:24 UTC, mysosnovskaya commented on src/main/java/faang/school/analytics/service/AnalyticsEventServiceImpl.java
> +            case HOUR -> date.isAfter(now.minusHours(1));
В задаче такого нет. Там просто идет речь про интервал, не факт, что единичной длины. Я думаю, если обратиться к аналитику, то он бы сказал, какие именно интервалы нам нужны, и скорее всего это были бы довольно разнообразные варианты. 
PS: чтобы решать такие вопросы оперативнее - пиши в чат в дискорде)

2024-10-16 13:24 UTC, merged