Запрос аналитики BJS2-26909
CorporationX/analytics_service pull request #201
Opened 2024-10-10 11:32 UTC by Peregruzochka

2024-10-10 12:00 UTC, 20cognosce requested changes

2024-10-10 12:00 UTC, 20cognosce commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +    private Map<TimeInterval, Supplier<LocalDateTime>> intervalConverter = new HashMap<>();
Ааа, тут саплаер
Это функция

Беру свои слова назад.
Но все равно переделай это через final поле в блоке инициализации

2024-10-10 12:00 UTC, 20cognosce commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +    private Map<TimeInterval, Supplier<LocalDateTime>> intervalConverter = new HashMap<>();
Бага не будет

2024-10-10 12:00 UTC, 20cognosce commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +        }
Но это всё равно плохо

2024-10-11 09:26 UTC, Peregruzochka commented
image
Чтением событий занимаются EventListener`ы, которые реализуются в других задачах
Каждый listener слушает свой топик. Service ничего не слушает, а только сохраняет аналитику в бд.
Я это понял так
Зачем мне тут реализовывать чтение аналитики из redis??
https://faang-school.atlassian.net/browse/BJS2-26905

2024-10-11 15:13 UTC, 20cognosce approved these changes

2024-10-11 15:13 UTC, 20cognosce commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +    private Map<TimeInterval, Function<LocalDateTime, LocalDateTime>> intervalConverter = new HashMap<>() {{
Почему не final
В конструкторе тогда делай

2024-10-11 15:15 UTC, merged