Анализ подписок (sub)
CorporationX/analytics_service pull request #202
Opened 2024-10-10 14:05 UTC by SharkB38

2024-10-11 03:49 UTC, ArstanSubanov approved these changes
Всё круто, проблем не вижу) Видимо, ты ещё не закончил, так как не увидел сохранения ивента, но проблем это вызвать не должно, ставлю апрув)

2024-10-11 04:05 UTC, SharkB38 commented
> Всё круто, проблем не вижу) Видимо, ты ещё не закончил, так как не увидел сохранения ивента, но проблем это вызвать не должно, ставлю апрув)

Да, пока еще в работе, просто заранее пр сделал, чтобы код было удобно смотреть другим людям

2024-10-11 11:20 UTC, soulasphyxia commented on build.gradle.kts
> +    implementation("com.fasterxml.jackson.core:jackson-databind:2.15.2")
ты сам это поставил, или оно само как то? я не уверен, что можно так версии менять

2024-10-11 11:20 UTC, soulasphyxia commented on build.gradle.kts
> +    implementation("com.fasterxml.jackson.core:jackson-databind:2.15.2")
или то, что нам скинула Маша, работает только с этой?

2024-10-11 11:39 UTC, SharkB38 commented on build.gradle.kts
> +    implementation("com.fasterxml.jackson.core:jackson-databind:2.15.2")
Не переживай, это я уже обратно откатил, просто кое что пробовал

2024-10-12 16:56 UTC, ArstanSubanov approved these changes

2024-10-15 11:56 UTC, soulasphyxia approved these changes

2024-10-15 17:51 UTC, mysosnovskaya requested changes

2024-10-15 17:51 UTC, mysosnovskaya commented on src/main/java/faang/school/analytics/dto/event/FollowerEventDto.java
> +    public void setReceiverId(Long receiverId) {
Вопрос на подумать:
не нужно ли сделать абстрактные методы setReceiverId, setActorId и setTimestamp в классе AbstractEventDto, чтобы другие разработчики, которые будут реализовывать этот класс, точно знали бы, что им нужно переопределить эти методы?

2024-10-15 17:51 UTC, mysosnovskaya commented on src/main/java/faang/school/analytics/mapper/AnalyticsEventMapper.java
> +    AnalyticsEvent toAnalyticsEventFromAbstractEvent(AbstractEventDto abstractEventDto);
Может просто toAnalyticsEvent? Благодаря полиморфизму можно будет иметь несколько разных методов с одинаковым названием, но разными передаваемыми параметрами, поэтому уточнять в названии метода FromAbstractEvent необязательно. А на мой взгляд даже излишне

2024-10-15 17:51 UTC, mysosnovskaya commented on src/main/java/faang/school/analytics/listener/FollowerEventListener.java
> +            log.error(e.getMessage(), e);
Писала Арстану, напишу и тебе: спринг точно сам не залоггирует RuntimeException, который ниже? Надо бы проверить, а то дублирование в логах будет

2024-10-16 13:48 UTC, SharkB38 commented on src/main/java/faang/school/analytics/listener/FollowerEventListener.java
> +            log.error(e.getMessage(), e);
Проверил, не логгирует

2024-10-16 19:34 UTC, mysosnovskaya approved these changes

2024-10-16 19:34 UTC, merged