Анализ покупок премиум подписок BJS2-27087
CorporationX/analytics_service pull request #210
Opened 2024-10-12 16:25 UTC by sultan-inked

2024-10-12 19:48 UTC, vestmen commented on src/main/java/faang/school/analytics/service/user/premium/listener/RedisPremiumBoughtEventSubscriber.java
> +public class RedisPremiumBoughtEventSubscriber implements MessageListener {
У тебя этот класс во многом дублирует RedisProfileViewEventSubscriber из твоей прошлой таски, я бы подумал об абстракции (как в лекции Влад рассказывает), чтобы избежать дублирования кода

2024-10-12 21:05 UTC, kripersh27 commented on src/main/java/faang/school/analytics/config/redis/RedisConfig.java
> +public class RedisConfig {
Так как мы используем спринг бут, тут много работает под капотом, я в конфиге редиса у себя оставил только бин RedisMessageListenerContainer и создание топика, и всё работает)

2024-10-12 21:05 UTC, kripersh27 commented on src/main/java/faang/school/analytics/config/redis/RedisConfig.java
> +public class RedisConfig {
Чтобы много лишнего не писать.

2024-10-12 21:05 UTC, kripersh27 commented on src/main/java/faang/school/analytics/config/scheduler/user/premium/PremiumBoughtEventSaveQuartzConfig.java
> +public class PremiumBoughtEventSaveQuartzConfig {
Мне кажется для данной задачи кварц избыточен, достаточно шедулед использовать, но тут и так и так можно, просто шедулед всего одна аннотация.

2024-10-12 21:05 UTC, ilu23ilu23 commented on src/main/java/faang/school/analytics/service/user/premium/listener/RedisPremiumBoughtEventSubscriber.java
> +    private final List<AnalyticsEvent> analyticsEvents = new CopyOnWriteArrayList<>();
Как и в юзер сервисе я писал, что лучше заменить на другую коллекцию, и с канкарентлинкедкью как раз от стнхронайзд избавишься

2024-10-12 21:14 UTC, sultan-inked commented on src/main/java/faang/school/analytics/service/user/premium/listener/RedisPremiumBoughtEventSubscriber.java
> +public class RedisPremiumBoughtEventSubscriber implements MessageListener {
Лекцию еще не смотрел, спасибо, так и сделаю

2024-10-12 21:15 UTC, sultan-inked commented on src/main/java/faang/school/analytics/config/redis/RedisConfig.java
> +public class RedisConfig {
Надо попробовать, спасибо

2024-10-12 21:16 UTC, sultan-inked commented on src/main/java/faang/school/analytics/config/scheduler/user/premium/PremiumBoughtEventSaveQuartzConfig.java
> +public class PremiumBoughtEventSaveQuartzConfig {
Я для закрепления использовал, что бы помнить как это настраивается, а так да

2024-10-12 21:16 UTC, sultan-inked commented on src/main/java/faang/school/analytics/service/user/premium/listener/RedisPremiumBoughtEventSubscriber.java
> +    private final List<AnalyticsEvent> analyticsEvents = new CopyOnWriteArrayList<>();
Да, согласен, на запись медленная, поменяю, спасибо

2024-10-16 13:06 UTC, sultan-inked commented on src/main/java/faang/school/analytics/config/redis/RedisConfig.java
> +public class RedisConfig {
У меня не работает без `JedisConnectionFactory`

2024-10-18 12:58 UTC, sultan-inked commented on src/main/java/faang/school/analytics/redis/listener/AbstractEventListener.java
Скопировал с пр Ильи

2024-10-18 17:38 UTC, 20cognosce requested changes

2024-10-18 17:38 UTC, 20cognosce commented on src/main/java/faang/school/analytics/service/user/listener/RedisProfileViewEventSubscriber.java
> +        return null;
Что это

2024-10-18 17:38 UTC, 20cognosce commented on src/main/java/faang/school/analytics/service/user/listener/RedisProfileViewEventSubscriber.java
> +    }
Это что
такого быть не должно, эксепшены тогда кидай, но само по себе это криво, потому что абстрактный класс ваш же

2024-10-18 17:38 UTC, 20cognosce commented on src/main/java/faang/school/analytics/service/user/premium/listener/RedisPremiumBoughtEventSubscriber.java
> +    }
/

2024-10-19 13:06 UTC, sultan-inked commented on src/main/java/faang/school/analytics/config/context/redis/RedisConfig.java
Удалил дубликат Алексея, появлся после мержа для решения конфликтов

2024-10-19 13:06 UTC, sultan-inked commented on src/main/java/faang/school/analytics/config/context/redis/RedisTopicsFactory.java
Дубликат

2024-10-19 13:08 UTC, sultan-inked commented on src/main/java/faang/school/analytics/config/redis/RedisMessageListenerContainerConfig.java
redisContainer принимает два вида листа слушателей, потому что в мастер залилось две реализации, Ильи и Алескандра, что бы не менять их логику объеденил создание контейнера

2024-10-19 16:12 UTC, sultan-inked commented on src/main/java/faang/school/analytics/config/redis/RedisMessageListenerContainerConfig.java
redisContainer принимает два вида листа слушателей, потому что в мастер залилось две реализации, Ильи и Алескандра, что бы не менять их логику объеденил создание контейнера

2024-10-19 16:12 UTC, sultan-inked commented on src/main/java/faang/school/analytics/config/redis/RedisMessageListenerContainerConfig.java
> +package faang.school.analytics.config.redis;
redisContainer принимает два вида листа слушателей, потому что в мастер залилось две реализации, Ильи и Алескандра, что бы не менять их логику объеденил создание контейнера

2024-10-19 16:13 UTC, sultan-inked commented on src/main/java/faang/school/analytics/config/context/redis/RedisConfig.java
Удалил дубликат Алексея, появлся после мержа для решения конфликтов

2024-10-19 16:13 UTC, sultan-inked commented on src/main/java/faang/school/analytics/config/context/redis/RedisTopicsFactory.java
Дубликат

2024-10-21 21:19 UTC, 20cognosce approved these changes

2024-10-21 21:20 UTC, merged