BJS2-27097 Анализ просмотров постов
CorporationX/analytics_service pull request #211
Opened 2024-10-12 19:33 UTC by vestmen

2024-10-12 20:22 UTC, sultan-inked commented on src/main/java/faang/school/analytics/redis/RedisConfig.java
> +    }
Мне кажется лучше вынести все что касается слушателя конкретного топика в отдельный класс, что бы общий конфиг редиса не засорять, топиков может быть много

2024-10-12 20:22 UTC, sultan-inked commented on src/main/java/faang/school/analytics/controller/AnalyticsEventController.java
> +    public ResponseEntity<List<AnalyticsEventDto>> getAnalytics(@RequestParam long receiverId,
Для чего реализовал ендпоинт получения аналитики, это разве есть в таске?

2024-10-12 20:22 UTC, sultan-inked commented on src/main/java/faang/school/analytics/controller/AnalyticsEventController.java
> +        AnalyticsRequestParams params = analyticsRequestService.processRequestParams(eventType, interval, from, to);
Какое то сложное получение по интервалу, может лучше два ендпоинта, но с валидацией двух видов интервалов, и можно избавится от кучи кода в этом сервисе, и сразу передать, имхо, может ошибаюсь

2024-10-12 20:39 UTC, vestmen commented on src/main/java/faang/school/analytics/controller/AnalyticsEventController.java
> +    public ResponseEntity<List<AnalyticsEventDto>> getAnalytics(@RequestParam long receiverId,
это я смержил ветку Ильи, чтобы я смог работать

2024-10-12 20:44 UTC, vestmen commented on src/main/java/faang/school/analytics/controller/AnalyticsEventController.java
> +        AnalyticsRequestParams params = analyticsRequestService.processRequestParams(eventType, interval, from, to);
Да, как-то коряво получилось влить изменения с мастера в свою, надо будет в следующий раз поподробнее разобраться

2024-10-12 21:29 UTC, ilu23ilu23 reviewed
В юзер сервисе я посмотрел, но не смог замечания написать)

2024-10-12 21:29 UTC, ilu23ilu23 commented on src/main/java/faang/school/analytics/listener/AbstractEventListener.java
> +            analyticsEventService.saveEvent(event);
Лучше пачками сохранять эвенты, я у Влада этот вопрос уточнял.

2024-10-12 21:29 UTC, ilu23ilu23 commented on src/main/java/faang/school/analytics/listener/AbstractEventListener.java
> +@Component
У абстрактного класса бин не создастся, лучше убрать эту аннотацию

2024-10-12 21:29 UTC, ilu23ilu23 commented on src/main/java/faang/school/analytics/listener/PostViewEventListener.java
> +public class PostViewEventListener extends AbstractEventListener<PostViewEventDto> implements MessageListener {
МесседжЛистенер лучше заимплементить в абстректном классе, чтобы потом наследники этого не делали.

2024-10-12 21:29 UTC, ilu23ilu23 commented on src/main/java/faang/school/analytics/redis/RedisConfig.java
> +public class RedisConfig {
Лучше создать пакет конфиг и вынести туда это вместе с пакетом редис

2024-10-14 10:03 UTC, vestmen commented on src/main/java/faang/school/analytics/listener/AbstractEventListener.java
> +            analyticsEventService.saveEvent(event);
в требованиях этого не было, поэтому я даже не думал об этом. Если Дима скажет поправлю))

2024-10-14 13:52 UTC, vestmen commented on src/main/java/faang/school/analytics/redis/RedisConfig.java
> +public class RedisConfig {
Cогласен

2024-10-14 13:54 UTC, vestmen commented on src/main/java/faang/school/analytics/redis/RedisConfig.java
> +    }
В лекциях Влад в одном все делал, потом контейнер будет разрастаться, будем добавлять туда разные container.addMessageListener(listenerAdapter, topic);

2024-10-16 21:04 UTC, 20cognosce requested changes
Конфликт поправить

2024-10-16 21:04 UTC, 20cognosce commented on src/main/java/faang/school/analytics/service/AnalyticsRequestService.java
> +        }
Это выглядит ужасно
Сделай красиво

2024-10-16 21:05 UTC, 20cognosce commented
И ребейз своей ветки не забудь сделать

2024-10-18 12:16 UTC, closed without merging