BJS2-27102 Анализ комментариев
CorporationX/analytics_service pull request #212
Opened 2024-10-12 20:40 UTC by ilu23ilu23

Функциональность чтения топик Редиса и сохранение полученной информации в бд.

2024-10-13 08:39 UTC, evgenywork commented on src/main/java/faang/school/analytics/redis/listener/CommentEventListener.java
> +    )
Ты кстати смотрел RetryTemplate ? это так для инфо.

2024-10-13 15:09 UTC, ilu23ilu23 commented on src/main/java/faang/school/analytics/redis/listener/CommentEventListener.java
> +    )
Да, это вручную прописывать, это как вместо аннотации Транзакшнл, использовать трнзакшнТемплейт

2024-10-13 17:16 UTC, sultan-inked commented on src/main/java/faang/school/analytics/redis/listener/CommentEventListener.java
> +
чтрочка)

2024-10-16 21:27 UTC, 20cognosce requested changes

2024-10-16 21:27 UTC, 20cognosce commented on src/main/java/faang/school/analytics/redis/listener/AbstractEventListener.java
> +    private final ConcurrentLinkedQueue<T> eventQueue = new ConcurrentLinkedQueue<>();
Еще один конструктор космолётов

2024-10-16 21:27 UTC, 20cognosce commented on src/main/java/faang/school/analytics/redis/listener/AbstractEventListener.java
> +        }
Убирай всё это

2024-10-16 21:27 UTC, 20cognosce commented on src/main/java/faang/school/analytics/redis/listener/AbstractEventListener.java
> +            eventQueue.add(event);
Пришло событие - сразу сохрани его в БД
Если хочешь много событий за раз - тогда в редис одним сообщением список отсылай

2024-10-16 21:27 UTC, 20cognosce commented on src/main/java/faang/school/analytics/redis/listener/AbstractEventListener.java
> +    @Scheduled(fixedRateString = "${event.listener.flushInterval}")
Вот представь, что твоя очередь на нагрузочном тестировании забьется быстрее чем выполнится твой flushInterval

и все ивенты испарятся, вуаля

А еще где ты обработал fail-safe механизм? Вот батч выдал ошибку, как нам ретрай делать или вернуть весь батч в очередь

ну вот и нафиг в аналитик сервисе это кеширование, вообще смысла тупо не вижу, лишнее нагромождение без профита

Ты ведь каждое событие просто добавляешь строчку в базу, какая разница добавить по 1 строчке 100 раз или 1 раз по 100 строчек, ну, в контексте этого сервиса разницы почти нет

2024-10-16 21:27 UTC, 20cognosce commented on src/main/java/faang/school/analytics/redis/listener/CommentEventListener.java
> +    @Retryable(
Хорошо, 3 ретрая есть
Если ты получишь все 3 ошибки, что тогда?

Ивенты испаряются

2024-10-16 21:27 UTC, 20cognosce commented on src/main/java/faang/school/analytics/redis/listener/CommentEventListener.java
> +    @Retryable(
Целый батч из 100 ивентов испаряется
офигенно

2024-10-17 09:50 UTC, sultan-inked commented on src/main/java/faang/school/analytics/redis/listener/CommentEventListener.java
> +    @Autowired
Если не ошибаюсь, то можно не писать `@Autowired`

2024-10-17 15:10 UTC, ilu23ilu23 commented on src/main/java/faang/school/analytics/redis/listener/CommentEventListener.java
> +    @Autowired
Можно, но мне так понятнее, когда вижу)

2024-10-17 21:07 UTC, 20cognosce approved these changes

2024-10-17 21:07 UTC, 20cognosce commented on src/main/java/faang/school/analytics/redis/listener/AbstractEventListener.java
> +            String messageBody = new String(message.getBody());
getBody что отдает? почему сразу не в объект парсишь

2024-10-17 21:07 UTC, 20cognosce commented on src/main/java/faang/school/analytics/redis/listener/CommentEventListener.java
> +            @Value("${spring.data.redis.channel.comment}") String commentEventChannel) {
Где проверка на null

2024-10-17 21:07 UTC, 20cognosce commented on src/main/java/faang/school/analytics/redis/listener/CommentEventListener.java
> +            ObjectMapper objectMapper,
Какой именно ты инжектишь

2024-10-18 12:13 UTC, sultan-inked commented on src/main/java/faang/school/analytics/config/redis/RedisConfig.java
> +    public RedisMessageListenerContainer redisContainer(
Предлагаю вынести этот метод в `RedisMessageListenerContainerConfig`

2024-10-18 12:18 UTC, ilu23ilu23 commented on src/main/java/faang/school/analytics/redis/listener/AbstractEventListener.java
> +            String messageBody = new String(message.getBody());
гет боди возвращает массив байт и это нужно, чтобы получить содержимое сообщения в формате, который можно передать в метод, сразу нельзя

2024-10-18 12:27 UTC, sultan-inked commented on src/main/java/faang/school/analytics/redis/listener/AbstractEventListener.java
> +
строчка

2024-10-18 12:27 UTC, sultan-inked commented on src/main/java/faang/school/analytics/redis/listener/AbstractEventListener.java
Я у тебя скопировал этот класс, если будут изменения сообщи пожалуйста

2024-10-18 18:41 UTC, 20cognosce approved these changes

2024-10-18 18:41 UTC, merged