v1 task: Анализ запросов на менторство / feature-BJS2-26160 / analytics_service
CorporationX/analytics_service pull request #215
Opened 2024-10-13 16:59 UTC by Varrankin

2024-10-13 21:44 UTC, Silencemess1ah reviewed
В общем PR ок, НО я не смотрел ничего из контроллера и сервиса, у меня была отдельная таска я уже смержил сервис логику и контроллер + интервалы все тоже(все это не смотрел) по Listener и конфигу ок, ед не уверен что с таким маппером оно заведеться + попробуй через постман прокинуть уверен будут сюрпризы с преобразованием JSON

2024-10-13 21:44 UTC, Silencemess1ah commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +}
Дим, там уже есть сервис и прочее, интервалы контролер и т.д. у меня отдельная таска была на это(

2024-10-13 21:44 UTC, Silencemess1ah commented on src/main/java/faang/school/analytics/mapper/MentorshipRequestMapper.java
> +    @Mapping(source = "requester", target = "actorId")
Бдует работать? requesterId же в сообщении из трубы называется, + receiverId никак не мапиться явно

2024-10-13 21:44 UTC, Silencemess1ah commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +    public void SaveAnalyticsEvent(AnalyticsEvent analyticsEvent) {
Большая буква в начале названия метода

2024-10-14 09:02 UTC, Varrankin commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +}
блин, сейчас вижу, обновил ветку и смерджил и подтянулись новые изменения, ты видимо недавно такску смержил? просто не было их когда я создавал ветку себе

2024-10-16 20:26 UTC, mysosnovskaya requested changes

2024-10-16 20:26 UTC, mysosnovskaya commented on src/main/java/faang/school/analytics/listener/MentorshipRequestEventListener.java
> +    private MentorshipRequestMapper mentorshipRequestMapper;
final

2024-10-16 20:26 UTC, mysosnovskaya commented on src/main/java/faang/school/analytics/listener/MentorshipRequestEventListener.java
> +            log.info("the message has been deserialized. MentorshipRequestMessage: {}", mentorshipRequestMessage);
debug тут лучше подойдет

2024-10-16 20:26 UTC, mysosnovskaya commented on src/main/java/faang/school/analytics/listener/MentorshipRequestEventListener.java
> +            log.info("MentorshipRequestMessage is mapped to AnalyticsEvent. AnalyticsEvent: {}", analyticsEvent);
debug тут лучше подойдет. Хотя вообще не думаю, что этот лог нужен)

2024-10-16 20:26 UTC, mysosnovskaya commented on src/main/java/faang/school/analytics/listener/MentorshipRequestEventListener.java
> +            analyticsEvent.setEventType(EventType.of(16));
Откуда здесь 16? Почему 16? Надо вынести в константу/в конфиг или придумать другое, более очевидное решение

2024-10-16 20:26 UTC, mysosnovskaya commented on src/main/java/faang/school/analytics/listener/MentorshipRequestEventListener.java
> +            log.info("AnalyticsEvent added filed EventType. AnalyticsEvent: {}", analyticsEvent);
debug тут лучше подойдет. Хотя вообще не думаю, что этот лог нужен)

2024-10-16 20:26 UTC, mysosnovskaya commented on src/main/java/faang/school/analytics/listener/MentorshipRequestEventListener.java
> +            throw new RuntimeException(e);
Проверь, логгируется ли это исключение спрингом?

2024-10-17 09:36 UTC, Varrankin commented on src/main/java/faang/school/analytics/listener/MentorshipRequestEventListener.java
> +            analyticsEvent.setEventType(EventType.of(16));
16 это индекс enum который нам возвращает нужный тип, так как это listener конкретного события то тип никогда не будет меняться, поэтому согласен что его можно вынести в константу, на счет конфига не уверен потому что данные не изменяемые

2024-10-17 09:40 UTC, Varrankin commented on src/main/java/faang/school/analytics/listener/MentorshipRequestEventListener.java
> +            log.info("AnalyticsEvent added filed EventType. AnalyticsEvent: {}", analyticsEvent);
согласен, я просто напихал логи везде, чтоб поучиться да и мне так отладку легче было проводить

2024-10-17 18:16 UTC, mysosnovskaya requested changes

2024-10-17 18:16 UTC, mysosnovskaya commented on src/main/java/faang/school/analytics/listener/MentorshipRequestEventListener.java
> +    private final int INDEX_TYPE = 16;
Такое решение не подойдет) А что если в енаме кто-то что-то изменит? Нельзя завязываться на то, как у нас в коде. Сделай поле EventType сразу с нужным значением перечисления, тогда мы будем застрахованы от удаления этого типа и от его переноса выше/ниже в перечислении.
Ну и константное поле должно быть static и располагаться в самом верху класса)

2024-10-18 12:13 UTC, Varrankin commented on src/main/java/faang/school/analytics/listener/MentorshipRequestEventListener.java
> +    private final int INDEX_TYPE = 16;
переделал, только не совсем понял, а как мы будем застрахованы от удаления конкретного типа в данном случае?

2024-10-18 13:52 UTC, Varrankin commented
все поправил, тесты написал

2024-10-18 18:27 UTC, mysosnovskaya commented on src/main/java/faang/school/analytics/listener/MentorshipRequestEventListener.java
> +    private final int INDEX_TYPE = 16;
Компилятор ругаться будет, ну или IDEA

2024-10-18 18:27 UTC, mysosnovskaya approved these changes

2024-10-22 14:34 UTC, merged

2024-10-24 16:02 UTC, mysosnovskaya commented on src/main/java/faang/school/analytics/listener/MentorshipRequestEventListener.java
> +            throw new RuntimeException(e);
Тест комментарий