Features/likes analysis bjs2 26904
CorporationX/analytics_service pull request #223
Opened 2024-10-15 11:51 UTC by DankeVilletti

Listener для postLike

2024-10-16 10:41 UTC, Peregruzochka reviewed
Как обстановочка с тестами?)

2024-10-16 10:41 UTC, Peregruzochka commented on src/main/java/faang/school/analytics/model/event/type/EventType.java
> +    //PROJECT_APPEARED_IN_SEARCH(Object.class);
Мб сделать какой-нибудь класс-маппер, который преобразует enum в нужный тебе класс?

2024-10-16 10:41 UTC, Peregruzochka commented on src/main/java/faang/school/analytics/model/event/type/service/post/like/PostLikeEvent.java
> +public class PostLikeEvent extends AbstractLikeEvent {
Почему бы не пойти по пути того, что листенер принимает PostLikeEventDto?
А потом еще один класс-маппер преобразует dto в AnalyticsEvent

2024-10-16 10:41 UTC, Peregruzochka commented on src/main/java/faang/school/analytics/model/event/type/service/post/like/AbstractLikeEvent.java
> +public abstract class AbstractLikeEvent {
А какой смысл в этом абстрактном классе?

2024-10-16 10:41 UTC, Peregruzochka commented on src/main/resources/application.yaml
> +        post-service:
зачем тут post-service? тип нет разницы в том, кто отправляет сообщения в брокер, тебе главное его принять

2024-10-16 14:09 UTC, DankeVilletti commented on src/main/java/faang/school/analytics/model/event/type/EventType.java
> +    //PROJECT_APPEARED_IN_SEARCH(Object.class);
для этого нужно в любом случае создать все классы соответствующие каждому enum

2024-10-16 14:10 UTC, DankeVilletti commented on src/main/java/faang/school/analytics/model/event/type/service/post/like/PostLikeEvent.java
> +public class PostLikeEvent extends AbstractLikeEvent {
в какой-то степени это DTO, сейчас поработаю над неймингом

2024-10-16 14:11 UTC, DankeVilletti commented on src/main/java/faang/school/analytics/model/event/type/service/post/like/AbstractLikeEvent.java
> +public abstract class AbstractLikeEvent {
Лайки есть еще и для комментариев

2024-10-16 14:12 UTC, DankeVilletti commented on src/main/resources/application.yaml
> +        post-service:
сервисов которые будут создавать каналы много, и в аналитику по одному каналу будет гарантировано приходить только от одного сервиса, для того чтобы читаемость была лучше, лучше каналы группировать по сервисам

2024-10-18 19:33 UTC, 20cognosce requested changes

2024-10-18 19:33 UTC, 20cognosce commented on src/main/java/faang/school/analytics/dto/event/type/service/post/like/PostLikeEventDto.java
> +        super(likedEntityId, authorId, userExciterId, createdAt);
Через аннотации ломбока нельзя это сделать?
Зачем ты тогда наследуешься, если ничего не меняется

2024-10-18 19:33 UTC, 20cognosce commented on src/main/java/faang/school/analytics/model/EventType.java
> +    //PROJECT_APPEARED_IN_SEARCH(Object.class);
Зачем ты это сделал...

2024-10-18 19:33 UTC, 20cognosce commented on src/main/java/faang/school/analytics/model/EventType.java
> +    //PROJECT_APPEARED_IN_SEARCH(Object.class);
Убери как было, ищи другой способ

2024-10-18 19:33 UTC, 20cognosce commented on src/main/java/faang/school/analytics/model/EventType.java
> +    //PROJECT_APPEARED_IN_SEARCH(Object.class);
Сделай поиск просто по имени, маппинг в switch case с дефолтным эксепшеном

2024-10-21 20:37 UTC, 20cognosce requested changes

2024-10-21 20:37 UTC, 20cognosce commented on src/main/java/faang/school/analytics/publish/listener/like/PostLikeEventListener.java
> +            System.out.println(message.toString());
бан

2024-10-21 20:37 UTC, 20cognosce commented on src/main/java/faang/school/analytics/publish/listener/like/PostLikeEventListener.java
> +            System.out.println(message.toString());
Ну вот что это? Как с этим вмёрджить

2024-10-24 20:25 UTC, 20cognosce approved these changes

2024-10-24 20:27 UTC, merged