Анализ лайков BJS2 26914
CorporationX/analytics_service pull request #227
Opened 2024-10-16 10:18 UTC by Peregruzochka

2024-10-17 10:44 UTC, Alginin commented on src/main/java/faang/school/analytics/listener/CommentEventListener.java
> +            throw new IllegalArgumentException("Error with mapping to CommentEventDto");
Ошибку можно залогировать

2024-10-18 18:38 UTC, 20cognosce requested changes

2024-10-18 18:38 UTC, 20cognosce commented on build.gradle.kts
> +    testImplementation("com.h2database:h2:2.2.224")
Не понял, нафига

2024-10-18 18:38 UTC, 20cognosce commented on src/main/resources/application-test.yaml
> +    password:
Тестконтейнерс bruh...

2024-10-18 18:38 UTC, 20cognosce commented on src/test/java/faang/school/analytics/listener/CommentEventListenerTest.java
> +            .withExposedPorts(6379);
Тем более, если ты редис поднимаешь по-нормальному
почему постгрес заменил суррогатом

2024-10-18 18:38 UTC, 20cognosce commented on src/test/java/faang/school/analytics/listener/CommentEventListenerTest.java
> +    @DynamicPropertySource
Все настройки в отдельную конфигурацию для тестов

2024-10-19 07:07 UTC, Peregruzochka commented on src/test/java/faang/school/analytics/listener/CommentEventListenerTest.java
> +            .withExposedPorts(6379);
Когда делал задание еще не знал что мы в git actions можем поднять redis

2024-10-19 09:34 UTC, Peregruzochka commented on src/test/java/faang/school/analytics/listener/CommentEventListenerTest.java
> +    @DynamicPropertySource
У нас в проекте уже есть класс BaseContextTest, в котором производятся все настройки Testcontainers. Могу ли я использовать его? Или обязательно нужно запихнуть все в TestConfiguration?

2024-10-21 20:45 UTC, 20cognosce approved these changes

2024-10-21 20:45 UTC, merged