настройка ci
CorporationX/analytics_service pull request #233
Opened 2024-10-17 09:47 UTC by Peregruzochka

2024-10-17 10:15 UTC, Alginin reviewed
Nice!

2024-10-17 10:15 UTC, Alginin commented on .github/workflows/ci.yaml
> +
Андрей как то писал:
"НАРОД! Если будите настраивать Redis, то на стороне где у вас принимаются данные(где MessageListener) ОБЯЗАТЕЛЬНО убедитесь что настроен CI Pipeline, а то будете как я мучаться когда у вас на компе все работает, а в Git билд падает."

2024-10-17 10:15 UTC, Alginin commented on .github/workflows/ci.yaml
> +          cache: 'gradle'
Это прям хорошо с кэшем

2024-10-18 12:06 UTC, 20cognosce requested changes

2024-10-18 12:06 UTC, 20cognosce commented on .github/workflows/ci.yaml
> +
Что это за пустые строки

2024-10-18 12:06 UTC, 20cognosce commented on .github/workflows/ci.yaml
> +      - kraken-master-stream6
Зачем на пуш? Только на пулл реквест запуск пайплайна

2024-10-18 12:06 UTC, 20cognosce commented on .github/workflows/ci.yaml
> +    runs-on: ubuntu-latest
А где постгрес, где редис?

2024-10-18 12:06 UTC, 20cognosce commented on .github/workflows/ci.yaml
> +    runs-on: ubuntu-latest
Напиши один тест на поднятие контекста, чтобы реально он запрашивал коннекшены, и тут добавь контейнеры

2024-10-18 15:28 UTC, 20cognosce approved these changes

2024-10-18 15:28 UTC, merged