BJS2-26158 - Created listener for project view event
CorporationX/analytics_service pull request #244
Opened 2024-10-17 20:52 UTC by GusevVrn

2024-10-18 14:03 UTC, Varrankin commented on src/test/java/faang/school/analytics/listener/ProjectViewEventListenerTest.java
> +    @DisplayName("When trying handle incoming message and user object mapper then throw exception")
я только вот твои тесты смотрю, и меня смущает что whenGotMessageThenSaveItInDatabase() не имеет утверждений, а далее ты тестишь что просто вылетают исключения, как будто это бессмысленно, не проверяешь никаких условий, я бы закинул проверку в первый тест что не вылетает исключений и остальные тесты удалил

2024-10-19 14:34 UTC, mysosnovskaya commented on src/test/java/faang/school/analytics/listener/ProjectViewEventListenerTest.java
> +    @DisplayName("When trying handle incoming message and user object mapper then throw exception")
@GusevVrn что скажешь?

2024-10-19 14:41 UTC, mysosnovskaya requested changes

2024-10-19 14:41 UTC, mysosnovskaya commented on src/main/java/faang/school/analytics/dto/event/AbstractEvent.java
> +public abstract class AbstractEvent {
Как же круто ты сделал!) Супер!) 
На моей практике такие абстрактные классы мы чаще всего называем со словом base вместо abstract (т.е. BaseEvent, BaseEventListener). Это непринципиально, можешь рассмотреть такой вариант и если твой нравится больше, то оставляй так

2024-10-19 14:41 UTC, mysosnovskaya commented on src/main/java/faang/school/analytics/dto/event/project/ProjectViewEvent.java
> +    @JsonProperty("userId")
С JsonProperty хорошо получилось 👍

2024-10-19 14:41 UTC, mysosnovskaya commented on src/main/java/faang/school/analytics/dto/event/project/ProjectViewEvent.java
> +    public void setActorId(long actorId) {
Опять предложу, а ты реши:
в AbstractEvent эти три сеттера можно сделать специально абстрактными и прописать явно, что каждый наследник был обязан их переопределить. Почему так: когда другой разработчик, незнакомый с твоей идеей, будет добавлять нового наследника, он может не заглянуть в уже имеющихся и не переопределить эти методы в соответствии с json. Понятно, что на тестировании он это выяснит, но так мы сможем сильно раньше явным образом показать, как должно быть. Т.е. это заставит этого будущего разработчика посмотреть в других наследниках, зачем же ему переопределять эти сеттеры

2024-10-19 14:41 UTC, mysosnovskaya commented on src/main/java/faang/school/analytics/listener/AbstractEventListener.java
> +    protected AnalyticsEvent mapEvent(AbstractEvent abstractEvent) {
mapToAnalyticsEvent может быть?

2024-10-19 20:46 UTC, GusevVrn commented on src/test/java/faang/school/analytics/listener/ProjectViewEventListenerTest.java
> +    @DisplayName("When trying handle incoming message and user object mapper then throw exception")
@mysosnovskaya ну мы словами обсудили это, в целом я согласен с Димой и он со мной))
Я сам считаю что часть тестов у нас бессмысленные в принципе. В самом начале я на такие тесты плевался но мы как-то вроде пришли к тому что имеет место быть таким тестам где ты сам полностью поведение определяешь.
Я стал придерживаться такой логике - покрытие кода имеет свой процент, этими тестами я добавляю +1 строчку к покрытию для каждого исключения) С другой стороны, а как я иначе проверю какой-нибудь readValue - если objectMapper это Mock.

2024-10-19 21:37 UTC, GusevVrn commented on src/main/java/faang/school/analytics/dto/event/project/ProjectViewEvent.java
> +    public void setActorId(long actorId) {
Что тут думать, ты все правильно расписала. Определяем некий контракт.

2024-10-20 19:18 UTC, mysosnovskaya approved these changes

2024-10-20 19:18 UTC, merged