Анализ посещаемости профиля проекта sub
CorporationX/analytics_service pull request #260
Opened 2024-10-19 10:05 UTC by RuslanIovlev

2024-10-19 10:17 UTC, soulasphyxia approved these changes

2024-10-19 10:23 UTC, SharkB38 requested changes

2024-10-19 10:23 UTC, SharkB38 commented on src/main/java/faang/school/analytics/dto/event/ProjectViewEvent.java
> +public class ProjectViewEvent extends AbstractEventDto{
Здесь пробел перед {

2024-10-19 11:54 UTC, ArstanSubanov approved these changes

2024-10-19 14:49 UTC, mysosnovskaya requested changes

2024-10-19 14:49 UTC, mysosnovskaya commented on src/main/java/faang/school/analytics/config/redis/RedisConfig.java
>              FollowerEventListener followerListener,
Тут как-то неединообразно получилось. Где-то с Qualifier, где-то без. Вот это нужно поправить точно.
Ну и к тому же количество параметров метода растет. Я бы предложила тебе как доп задачку подумать над упрощением (чтобы с каждым новым топиком количество параметров не увеличивалось). У меня есть некоторая идея, поэтому если захочешь, можем обсудить)

2024-10-20 11:26 UTC, wmwmaks commented on src/main/java/faang/school/analytics/dto/event/ProjectViewEvent.java
> +public class ProjectViewEvent extends AbstractEventDto {
Что думаете насчет снова начать добавлять в конец Dto к названию классов этих?

2024-10-20 11:28 UTC, wmwmaks commented on src/main/java/faang/school/analytics/dto/event/ProjectViewEvent.java
> +    @JsonProperty("guestId")
Не знал про эту аннотацию 👍

2024-10-20 11:30 UTC, wmwmaks approved these changes
👍

2024-10-21 09:15 UTC, RuslanIovlev commented on src/main/java/faang/school/analytics/dto/event/ProjectViewEvent.java
> +public class ProjectViewEvent extends AbstractEventDto {
Хороший вопрос, тоже видел что все по разному делают

2024-10-21 19:19 UTC, mysosnovskaya reviewed
И конфликты поправь)

2024-10-21 19:19 UTC, mysosnovskaya commented on src/main/java/faang/school/analytics/config/redis/RedisConfig.java
> +        container.addMessageListener(listenerAdapters.get("followerListener"), channelTopics.get("followerEventTopic"));
Тут можно сделать for-each по мапе listenerAdapters и для каждого ключа из нее взять соответствующее значение из channelTopics. Чтобы руками не прописывать названия бинов. 
Вообще здорово, что ты подсмотрел идею у Арстана, лайк за перенимание опыта 👍 А у него тоже через такие get было?) Если да, то можешь написать ему мой коммент :D

2024-10-24 12:49 UTC, RuslanIovlev commented
немного поменял redisconfig, чтобы все в одном стиле было, а также отредактировал dto

2024-10-24 12:49 UTC, RuslanIovlev commented
локально запустил, сервис работает

2024-10-24 17:54 UTC, mysosnovskaya approved these changes

2024-10-24 17:54 UTC, merged