feature-BJS2-26161: Анализ просмотров постов (analytics_service)
CorporationX/analytics_service pull request #264
Opened 2024-10-19 20:35 UTC by StepnovaVarvara

2024-10-20 13:11 UTC, GusevVrn reviewed
Так, есть один вопрос на подумать и он относится к интеграции между сервисами.

И один вопрос общий, пишу тут, ты с полями разобралась для BaseEvent, кто за что отвечает?

2024-10-20 13:11 UTC, GusevVrn commented on src/main/java/faang/school/analytics/config/redis/RedisConfiguration.java
> +public class RedisConfiguration {
так же модификаторы доступа всем проставь

2024-10-20 13:11 UTC, GusevVrn commented on src/main/java/faang/school/analytics/dto/BaseEvent.java
> +    public BaseEvent(Long receiverId, Long actorId, LocalDateTime receivedAt) {
ну щас видимо кто первый запушится, либо через конструктор либо через сеттеры будем делать

2024-10-20 13:11 UTC, GusevVrn commented on src/main/java/faang/school/analytics/dto/post/PostViewEvent.java
> +@Setter
нужен сеттер?

2024-10-20 13:11 UTC, GusevVrn commented on src/main/java/faang/school/analytics/dto/post/PostViewEvent.java
> +    private long postId;
пост какую смысловую нагрузку несет?

2024-10-20 13:11 UTC, GusevVrn commented on src/main/java/faang/school/analytics/dto/post/PostViewEvent.java
> +    private Long userId;
а юзер как здесь появится?

2024-10-21 20:05 UTC, StepnovaVarvara commented on src/main/java/faang/school/analytics/config/redis/RedisConfiguration.java
> +public class RedisConfiguration {
поставила

2024-10-21 20:06 UTC, StepnovaVarvara commented on src/main/java/faang/school/analytics/dto/post/PostViewEvent.java
> +    private long postId;
у меня по задачке эти поля нужно добавть

2024-10-21 20:07 UTC, StepnovaVarvara commented on src/main/java/faang/school/analytics/dto/post/PostViewEvent.java
> +    private Long userId;
Тоже об этом думала! По условию задачки это поле нужно добавить, но фактически оно пустое, тк в сервис юзер не попадает. Я бы убрала

2024-10-21 20:09 UTC, StepnovaVarvara commented on src/main/java/faang/school/analytics/dto/BaseEvent.java
> +    public BaseEvent(Long receiverId, Long actorId, LocalDateTime receivedAt) {
Хорошо, но мне через конструктор понятнее чтоли...

2024-10-22 17:30 UTC, StepnovaVarvara commented
> Так, есть один вопрос на подумать и он относится к интеграции между сервисами.
> 
> И один вопрос общий, пишу тут, ты с полями разобралась для BaseEvent, кто за что отвечает?

Ну я сделала 3 поля для всех. receiverId - это тот с кем что-то сделали, actorId - тот, кто сделал, ну и время действия. Но мне кажется, что у нас может произойти такая ситуация, что не будет actorId. У меня было подобное в какой-то задачке: по заданию требовался id юзера, который просмотрел пост, но в самом сервисе неоткуда было брать эту информацию.

2024-10-22 17:30 UTC, StepnovaVarvara commented on src/main/java/faang/school/analytics/dto/post/PostViewEvent.java
> +@Setter
Убрала

2024-10-22 20:09 UTC, mysosnovskaya requested changes

2024-10-22 20:09 UTC, mysosnovskaya commented on src/main/java/faang/school/analytics/config/redis/RedisConfiguration.java
> +public class RedisConfiguration {
Обрати внимание, в мастере уже появился такой класс, нужно его подтянуть

2024-10-22 20:09 UTC, mysosnovskaya commented on src/main/java/faang/school/analytics/dto/post/PostViewEvent.java
> +    private Long userId;
Для аналитики это важное поле, убирать не нужно. Я не поняла, почему он здесь появиться не может?

2024-10-22 20:09 UTC, mysosnovskaya commented on src/main/java/faang/school/analytics/listener/PostViewEventListener.java
> +public class PostViewEventListener extends AbstractEventListener<PostViewEvent> {
Красиво с абстракцией получилось, ты молодец 👍

2024-10-23 17:34 UTC, StepnovaVarvara commented on src/main/java/faang/school/analytics/listener/PostViewEventListener.java
> +public class PostViewEventListener extends AbstractEventListener<PostViewEvent> {
Переделала

2024-10-23 17:35 UTC, StepnovaVarvara commented on src/main/java/faang/school/analytics/config/redis/RedisConfiguration.java
> +public class RedisConfiguration {
Готово

2024-10-23 17:47 UTC, StepnovaVarvara commented on src/main/java/faang/school/analytics/dto/post/PostViewEvent.java
> +    private Long userId;
Помогла, я сделала

2024-10-23 19:08 UTC, mysosnovskaya approved these changes

2024-10-23 19:09 UTC, mysosnovskaya commented
Поправь конфликты и можешь оба ПРа мержить

2024-10-23 19:25 UTC, merged