BJS2-41431 Сохранение и получение аналитики
CorporationX/analytics_service pull request #289
Opened 2024-12-01 12:44 UTC by frs717

2024-12-01 14:03 UTC, frs717 commented on src/main/java/faang/school/analytics/controller/AnalyticsEventController.java
> +public class AnalyticsEventController {
Посмотрел другие задачки. Я как понял, в этой не нужно было создавать контроллер

2024-12-02 20:15 UTC, MiraGlaceon commented on src/main/java/faang/school/analytics/controller/AnalyticsEventController.java
> +            @RequestParam Long receiverId,
Много параметров, почему решил не помещать в DTO?

2024-12-04 16:32 UTC, frs717 commented on src/main/java/faang/school/analytics/controller/AnalyticsEventController.java
> +            @RequestParam Long receiverId,
Нашел способ. Оно упаковывается в @ ModelAttribute

2024-12-06 15:53 UTC, MiraGlaceon requested changes
Давай еще напишем обработчик ошибок для контроллера и протестируем его. Протестировать можно с помощью mockMVC

2024-12-06 15:53 UTC, MiraGlaceon commented on src/main/java/faang/school/analytics/controller/AnalyticsEventController.java
> +        if (event.getId() != null) {
Эту проверку сохранения нужно вынести так же в сервис analyticsEventService.saveEvent

2024-12-06 15:53 UTC, MiraGlaceon commented on src/main/java/faang/school/analytics/controller/AnalyticsEventController.java
> +            log.warn("Attempt save event with id");
1) Тут у тебя лог запутывает. У тебя нулевой айдишник, ты уже не можешь его сохранить, а в логе пишешь "попытка сохранить событие".
2) Саму проверку на нулевой айдишник предоставь аннотации @Valid, а в ДТО проставь NotNull

2024-12-06 15:53 UTC, MiraGlaceon commented on src/main/java/faang/school/analytics/controller/AnalyticsEventController.java
> +        if (filterDto.getInterval() != null && (filterDto.getFrom() != null || filterDto.getTo() != null)) {
Эти проверки так же вынеси в сервис

2024-12-06 15:53 UTC, MiraGlaceon commented on src/main/java/faang/school/analytics/controller/AnalyticsEventController.java
> +    public List<AnalyticsEventDto> getEvents(@ModelAttribute @Valid AnalyticsEventFilterDto filterDto) {
Отличное решение с ModelAttribute 👍

2024-12-06 15:53 UTC, MiraGlaceon commented on src/main/java/faang/school/analytics/model/Interval.java
> +package faang.school.analytics.model;
В пакете model лежат сущности, а у тебя enum, вынеси его в пакет другого уровня

2024-12-06 15:53 UTC, MiraGlaceon commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +package faang.school.analytics.service;
Тут желательно создать подпакет для аналитики событий

2024-12-06 15:53 UTC, MiraGlaceon commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +    protected Stream<AnalyticsEvent> filterByInterval(Stream<AnalyticsEvent> events, int interval) {
Почему protected, а не private? Если подразумевается, что будут разные сервисы и у всех будут фильтры разные по интервалу и датам, то вынести в интерфейс логику.  Но я вижу что у тебя здесь нет проблем, которые можно было бы заложить для расширения, тогда может все таки private?

2024-12-10 19:39 UTC, MiraGlaceon approved these changes

2024-12-10 19:42 UTC, MiraGlaceon approved these changes

2024-12-10 19:42 UTC, MiraGlaceon commented on src/main/java/faang/school/analytics/controller/advices/DataValidationControllerAdvice.java
> +    public ResponseEntity<ErrorMessageDto> handle(DataValidationException e) {
ResponseEntity можно так же не писать как и в контроллерах, сразу возвращать объект, спринг сам обернет объект в ResponseEntity. А код badRequest можно повесить аннотацией

2024-12-11 14:45 UTC, merged