Feature save and get AnalyticsEvent
CorporationX/analytics_service pull request #292
Opened 2024-12-02 23:36 UTC by DeemaP

add '/api/v1' context path
add Interval enum
add base functions for AnalyticsEvent.
add Junit tests

2024-12-03 09:28 UTC, YTXIRE requested changes

2024-12-03 09:28 UTC, YTXIRE commented on src/main/java/faang/school/analytics/dto/analyticsEvent/AnalyticsEventFilterDto.java
> +@Builder
AllArgsConstructor не нужен тебе тут?)

2024-12-03 09:28 UTC, YTXIRE commented on src/main/java/faang/school/analytics/dto/analyticsEvent/AnalyticsEventResponseDto.java
> +public class AnalyticsEventResponseDto {
И тут так же AllArgsConstructor)

2024-12-03 09:28 UTC, YTXIRE commented on src/main/java/faang/school/analytics/filter/AnalyticsEventFromToFilter.java
> +public class AnalyticsEventFromToFilter implements Filter<AnalyticsEvent, AnalyticsEventFilterDto> {
Как мне кажется, что лучше разделить два фильтра, бывают случаи, когда нужно фильтрануть по дате от или по дате до.

2024-12-03 09:28 UTC, YTXIRE commented on src/main/java/faang/school/analytics/model/Interval.java
> +public enum Interval {
Почему данный класс в model лежит?
Модели - это же представление базы данных

2024-12-03 09:28 UTC, YTXIRE commented on src/main/java/faang/school/analytics/model/Interval.java
> +        LocalDateTime now = LocalDateTime.now(ZoneId.of("UTC"));
UTC+0? Может мск?

2024-12-03 20:10 UTC, DeemaP commented on src/main/java/faang/school/analytics/filter/AnalyticsEventFromToFilter.java
> +public class AnalyticsEventFromToFilter implements Filter<AnalyticsEvent, AnalyticsEventFilterDto> {
Дык я как раз так и сделал)
По условию задачи надо, что если Interval не задали, то применялись фильтры From To
И здесь они применяются по очереди. 
Если хочешь отфильтровать только from - пожалуйста, не пиши to)

2024-12-03 20:12 UTC, DeemaP commented on src/main/java/faang/school/analytics/model/Interval.java
> +        LocalDateTime now = LocalDateTime.now(ZoneId.of("UTC"));
Я везде у нас по проекту делал UTC+0
Независимо от того кто и где запустит проект) А то у нас команда от -8 до +7 :D

2024-12-03 20:12 UTC, DeemaP commented on src/main/java/faang/school/analytics/dto/analyticsEvent/AnalyticsEventFilterDto.java
> +@Builder
Добавил)

2024-12-03 20:12 UTC, DeemaP commented on src/main/java/faang/school/analytics/dto/analyticsEvent/AnalyticsEventResponseDto.java
> +public class AnalyticsEventResponseDto {
И тут)

2024-12-03 20:19 UTC, DeemaP commented on src/main/java/faang/school/analytics/model/Interval.java
> +public enum Interval {
Я поглядел, у нас по всем микросервисам  enums лежат в entity или model (в зависимости от названия в конкретном сервисе)

Я думаю мы обсудим этот вопрос завтра на созвоне или может Руслан поправит, пока что я оставлю как есть)

2024-12-03 22:22 UTC, pearacle123 commented on src/main/java/faang/school/analytics/dto/analyticsEvent/AnalyticsEventFilterDto.java
> +    LocalDateTime to;
Может быть такое, что to будет раньше, чем from?

2024-12-03 22:22 UTC, pearacle123 commented on src/main/java/faang/school/analytics/filter/AnalyticsEventFromToFilter.java
> +        return isIntervalNull && isFromOrToPresent;
```java
return filters.getInterval() == null && (filters.getFrom() != null || filters.getTo() != null);
```
Почему бы не написать так?

2024-12-03 22:22 UTC, pearacle123 commented on src/main/java/faang/school/analytics/model/Interval.java
> +        if (interval instanceof Duration) {
Почему бы нельзя сделать так?
```java
public LocalDateTime calculateIntervalStart() {
    LocalDateTime now = LocalDateTime.now(ZoneId.of("UTC"));
    return now.minus(interval);
}
```

2024-12-03 22:22 UTC, pearacle123 commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +    @Transactional(readOnly = true)
readOnly - круто, интересная штученция, изучу завтра утром

2024-12-03 22:39 UTC, DeemaP commented on src/main/java/faang/school/analytics/model/Interval.java
> +        if (interval instanceof Duration) {
Ох. я тут вчера закопался, действительно так можно сделать, ведь interval объявлен как TemporalAmount
а Duration и Period оба реализуют TemporalAmount, собсна все кайф)

Поправил

2024-12-03 22:49 UTC, DeemaP commented on src/main/java/faang/school/analytics/filter/AnalyticsEventFromToFilter.java
> +        return isIntervalNull && isFromOrToPresent;
Я вообще выпилил фильтры))

2024-12-03 22:50 UTC, DeemaP commented on src/main/java/faang/school/analytics/filter/AnalyticsEventFromToFilter.java
> +        return isIntervalNull && isFromOrToPresent;
Но то, как я написал сделано для читаемости))

2024-12-03 22:51 UTC, DeemaP commented on src/main/java/faang/school/analytics/dto/analyticsEvent/AnalyticsEventFilterDto.java
> +    LocalDateTime to;
прекрасное замечание, ща сделаю валидацию на это)

2024-12-04 01:15 UTC, DeemaP commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +    @Transactional(readOnly = true)
Если честно, я ее указал, поскольку у меня приложение не запускалось, там из базы возвращается стрим, поэтому спринг требовал повесить эту аннотацию

В новой версии вообще нет @Transactional, поскольку вся фильтрация на стороне базы и в сервисе просто один запрос отправляется)

2024-12-04 08:13 UTC, YTXIRE approved these changes

2024-12-04 19:32 UTC, RuslanZinovyev commented on src/main/java/faang/school/analytics/controller/AnalyticsEventController.java
> +    @GetMapping("/receiverId/{receiverId}/eventType/{eventType}")
`/receivers/{receiverId}/event-type/{eventType}`

2024-12-04 19:32 UTC, RuslanZinovyev commented on src/main/java/faang/school/analytics/controller/AnalyticsEventController.java
> +    @GetMapping("/receiverId/{receiverId}/eventType/{eventType}")
`/receivers/{receiverId}/event-type/{eventType}`

2024-12-04 19:32 UTC, RuslanZinovyev commented on src/main/java/faang/school/analytics/model/Interval.java
> +public enum Interval {
Можете создать пакет `enums `в папке модели  и положить туда, либо сделать вложенным классом другого класса если этим энумератором пользуется один конкретный класс

2024-12-04 19:32 UTC, RuslanZinovyev commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +        List<AnalyticsEventResponseDto> result = analyticsEventRepository.findAll(specification).stream()
Должно быть производительнее если мы будем сортировать на уровне базы:

```
    Sort sort = Sort.by(Sort.Direction.DESC, "receivedAt");

    List<AnalyticsEventResponseDto> result = analyticsEventRepository.findAll(specification, sort).stream()
            .map(analyticsEventMapper::entityToResponseDto)
            .toList();
```

2024-12-04 19:32 UTC, RuslanZinovyev commented on src/main/java/faang/school/analytics/specification/AnalyticsEventSpecification.java
> +            return null;
А можно сделать так чтобы null не возвращать?

```
public static Specification<AnalyticsEvent> withinPeriod(LocalDateTime start, LocalDateTime end) {
    return (root, query, criteriaBuilder) -> {
        Predicate predicate = criteriaBuilder.conjunction();

        if (start != null && end != null) {
            predicate = criteriaBuilder.between(root.get("receivedAt"), start, end);
        } else if (start != null) {
            predicate = criteriaBuilder.greaterThanOrEqualTo(root.get("receivedAt"), start);
        } else if (end != null) {
            predicate = criteriaBuilder.lessThanOrEqualTo(root.get("receivedAt"), end);
        }

        return predicate;
    };
}
```

2024-12-04 19:34 UTC, DeemaP commented on src/main/java/faang/school/analytics/controller/AnalyticsEventController.java
> +    @GetMapping("/receiverId/{receiverId}/eventType/{eventType}")
ой да, опять в ночи забыл про kebab-case

2024-12-04 20:04 UTC, DeemaP commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +        List<AnalyticsEventResponseDto> result = analyticsEventRepository.findAll(specification).stream()
Спасибо за подсказку! Реализовал

2024-12-04 20:14 UTC, DeemaP commented on src/main/java/faang/school/analytics/specification/AnalyticsEventSpecification.java
> +            return null;
Спасибо за это уточнение!
Действительно так гораздо правильнее, ведь мы не бросаем нигде null, а возвращаем просто предикат с true внутри! Круто))

2024-12-04 20:35 UTC, RuslanZinovyev approved these changes

2024-12-04 20:35 UTC, merged