Feature/bjs2 41427 - saving premium bought analytics
CorporationX/analytics_service pull request #303
Opened 2024-12-05 10:20 UTC by aplavina

2024-12-07 08:25 UTC, bozhedar commented on src/main/java/faang/school/analytics/service/analytic/AnalyticsEventService.java
> +    public void saveAction(AnalyticsEvent analyticsEvent) {
сервисы вроде должны принимать дто, посмотри как Иван дто сделал, у него задаче это было

2024-12-07 15:11 UTC, MiraGlaceon requested changes

2024-12-07 15:11 UTC, MiraGlaceon commented on src/main/java/faang/school/analytics/config/redis/RedisConfig.java
> +    RedisMessageListenerContainer redisContainer() {
Тут модификаторы доступа не забывай использовать. Не критично, спринг в любом случае найдет бин, но код стайл ломает без необходимости

2024-12-07 15:11 UTC, MiraGlaceon commented on src/main/java/faang/school/analytics/messaging/premium/PremiumBoughtListener.java
> +            throw new RuntimeException(e);
Залогировать ошибку с пояснением тоже следует

2024-12-07 15:11 UTC, MiraGlaceon commented on src/main/java/faang/school/analytics/service/analytic/AnalyticsEventService.java
> +    public void saveAction(AnalyticsEvent analyticsEvent) {
Да, тут согласен. Сущности передаем только из сервиса в репозиторий, между сервисами данные должны передаваться в DTO, в этом много плюсов, от сокрытия важных данных, которые нужны только при сохранении, либо поля аудита, которые собственно и не нужно передавать в объектах, они формируются при сохранении

2024-12-07 15:11 UTC, MiraGlaceon commented on src/main/resources/application.yaml
> +  topic:
Давай создадим еще один уровень name. Чтобы можно было добавлять другие топики тоже с разными именами

2024-12-07 15:12 UTC, MiraGlaceon commented
Тебе в этой реализации не нужен RedisTemplate<String, Object>, посмотри возможность убрать его

2024-12-29 10:22 UTC, aplavina commented on src/main/resources/application.yaml
> +  topic:
по-другому уже решили сделать как я поняла

2025-01-08 15:34 UTC, MiraGlaceon approved these changes

2025-01-08 15:36 UTC, MiraGlaceon commented on src/main/resources/application.yaml
> +  topic:
Да, обсуждали, неправильно сделали немного. Name нужно в общую группу было вынести, а не в каждом топике. В целом и без него ок, хотелось больше информативности в конфигах

2025-01-09 08:42 UTC, merged