BJS2-41438 - Анализ запросов на менторство
CorporationX/analytics_service pull request #321
Opened 2024-12-09 13:37 UTC by Shakhaev

2024-12-10 09:52 UTC, bozhedar reviewed
Привет, всё хорошо, единственное не понял зачем фильтр

2024-12-10 09:52 UTC, bozhedar commented on src/main/java/faang/school/analytics/service/events/AnalyticsEventFilter.java
> +
Не совсем понял зачем фильтр для твоей задачи

2024-12-10 09:52 UTC, bozhedar commented on src/main/java/faang/school/analytics/service/events/AnalyticsEventFilter.java
> +                .filter(e -> isDateBetween(e.getReceivedAt(), from, to));
ещё можно попробовать реализацию  через .anyMatch(e -> e.getReceivedAt.isAfter(from) && e.getReceivedAt.isBefore(to))) вместо .filter

2024-12-10 10:35 UTC, Shakhaev commented on src/main/java/faang/school/analytics/service/events/AnalyticsEventFilter.java
> +
@bozhedar Привет. А я у Вани реализацию скопировал, потом понял, что фильтр то мне и не нужен, забыл удалить и закоммитил.

2024-12-13 19:43 UTC, MiraGlaceon requested changes

2024-12-13 19:43 UTC, MiraGlaceon commented on src/main/java/faang/school/analytics/config/RedisConfig.java
> +    ChannelTopic mentorshipRequestedTopic() {
Пропустил модификатор доступа

2024-12-13 19:43 UTC, MiraGlaceon commented on src/main/java/faang/school/analytics/listener/mentorshiprequest/MentorshipRequestedEventListener.java
> +            log.error("Error reading value");
Тут добавь информативность в логе. У Message есть метод, который возвращает имя топика

2024-12-13 19:43 UTC, MiraGlaceon commented on src/main/java/faang/school/analytics/mapper/mentorshiprequest/MentorshipRequestEventMapper.java
> +    EventType mentorship_requested = EventType.MENTORSHIP_REQUESTED;
Тут зачем используешь такой подход? Почему не положить сразу EventType.MENTORSHIP_REQUESTED?

2024-12-15 13:43 UTC, MiraGlaceon approved these changes

2024-12-15 13:43 UTC, MiraGlaceon commented on src/main/java/faang/school/analytics/mapper/events/AnalyticsEventMapper.java
> +    AnalyticsEventDto recommendationToAnalyticsDto(RecommendationEvent recommendationEvent);
Это работает?
Богдан говорит у него на этом месте ошибка выходит, якобы не воспринимается enum. Если есть время, то попробуй с ним обсудить момент этот

2024-12-15 14:26 UTC, merged