BJS2-41352 реализовал логику создания и получения аналитики
CorporationX/analytics_service pull request #340
Opened 2024-12-12 21:27 UTC by evgen-backend-rostov

2024-12-12 21:33 UTC, evgen-backend-rostov commented on src/main/java/faang/school/analytics/controller/AnalyticsController.java
> +            @RequestParam("id")
@jibulani Женя, привет! Очень нужны твои советы по коду)

Вот этот блок с параметрами метода совсем мне не нравится: громоздко получается и совсем не читабельно как-то. Такое ощущение, что лучше для такого количества параметров @RequestParam лучше не использовать и передавать всё в боди

2024-12-12 21:37 UTC, evgen-backend-rostov commented on src/main/java/faang/school/analytics/mapper/GetAnalyticsRqMapper.java
> +                intervalDto = IntervalDto.valueOf(interval.toUpperCase());
С маппером, возможно, тоже перемудрил. Особенно с преобразованием строки в энам. Но лучше не смог придумать, как обработать и привести к одному виду прилетевшие параметры

2024-12-12 21:42 UTC, evgen-backend-rostov commented on src/main/java/faang/school/analytics/service/implementations/AnalyticsServiceImpl.java
> +    private Period generatePeriod(IntervalDto intervalDto, LocalDateTime from, LocalDateTime to, Integer count) {
вот этот метод результат даёт нужный, но выглядит как-то топорно...

Были у меня надежды заявиться после этого обучения на уровень мидла, но по ощущениям этот код на мидловский не тянет 🙁

2024-12-14 22:06 UTC, jibulani requested changes
хорошо, есть несколько некритичных замечаний
напиши еще тест на контроллер с помощью mockMvc

2024-12-14 22:06 UTC, jibulani commented on src/main/java/faang/school/analytics/controller/AnalyticsController.java
> +            @RequestParam("id")
да, это жестко :D
можно объединить параметры в класс и передать сюда аргумент этого класса без аннотаций, тогда спринг поймет, что каждое из полей это отдельный параметр
https://stackoverflow.com/questions/16942193/spring-mvc-complex-object-as-get-requestparam

2024-12-14 22:06 UTC, jibulani commented on src/main/java/faang/school/analytics/dto/AnalyticsCreateEventDto.java
> +        @NotBlank(message = "event is blank")
не надо одновременно использовать NotNull и NotBlank, потому что NotBlank включает в себя проверку на NotNull
https://www.baeldung.com/java-bean-validation-not-null-empty-blank

2024-12-14 22:06 UTC, jibulani commented on src/main/java/faang/school/analytics/mapper/GetAnalyticsRqMapper.java
> +@Component
зачем делать компонентом?
тебе же для маппинга ничего не требуется от других бинов, достаточно просто сделать статическим метод маппинга и по имени класса его вызывать

2024-12-14 22:06 UTC, jibulani commented on src/main/java/faang/school/analytics/mapper/GetAnalyticsRqMapper.java
> +                intervalDto = IntervalDto.valueOf(interval.toUpperCase());
так нормально, можно было бы внутри IntervalDto сделать статический метод, который возвращает IntervalDto, то есть внутри этого метода будет то, что ты тут написал `return IntervalDto.valueOf(interval.toUpperCase());`

2024-12-14 22:06 UTC, jibulani commented on src/main/java/faang/school/analytics/service/implementations/AnalyticsServiceImpl.java
> +            switch (intervalDto) {
в java 17 можно немного красивее реорганизовать код
```
beginDate = switch (intervalDto) {
            case DAY -> endDate.minusDays(param);
            case WEEK -> endDate.minusWeeks(param);
            case MONTH -> endDate.minusMonths(param);
            case YEAR -> endDate.minusYears(param);
        };
```

2024-12-14 22:06 UTC, jibulani commented on src/main/java/faang/school/analytics/service/implementations/AnalyticsServiceImpl.java
> +            }
если интервал приоритетнее чем from-to, то лучше его тут сразу возвращать, чтобы следующая проверка не перезатерла эти вычисления

2024-12-14 22:06 UTC, jibulani commented on src/main/java/faang/school/analytics/service/implementations/AnalyticsServiceImpl.java
> +            beginDate = from;
лучше чтобы переменные были неизменяемыми, меньше шансов ошибиться, можно сразу вернуть `Period(from, to)`

2024-12-14 22:06 UTC, jibulani commented on src/main/java/faang/school/analytics/service/implementations/AnalyticsServiceImpl.java
> +        return new Period(beginDate, endDate);
а если предыдущие if-ы не выполнились, то тут логичнее ошибку валидации кинуть о том, что невозможно вычислить период

2024-12-14 22:06 UTC, jibulani commented on src/main/java/faang/school/analytics/service/implementations/AnalyticsServiceImpl.java
> +    private Period generatePeriod(IntervalDto intervalDto, LocalDateTime from, LocalDateTime to, Integer count) {
вполне нормальный код, местами можно оптимизировать, но на мидла тянет :)

к тому же у тебя есть база знаний о работе веба, так что на мой взгляд точно можешь на мидла претендовать через пару-тройку спринтов, когда еще с базами данных поработаешь + подтянешь теорию хотя бы на основе вопросов из квизов

2024-12-14 22:06 UTC, jibulani commented on src/test/java/faang/school/analytics/mapper/GetAnalyticsRqDtoMapperTest.java
> +        getAnalyticsRqMapper = new GetAnalyticsRqMapper();
зачем это делать перед каждым тестом? недостаточно было проинициализировать при объявлении?

2024-12-14 22:06 UTC, jibulani commented on src/main/java/faang/school/analytics/service/implementations/AnalyticsServiceImpl.java
> +    private Period generatePeriod(IntervalDto intervalDto, LocalDateTime from, LocalDateTime to, Integer count) {
а при хорошей проработке легенды (например, что уже давно работаешь как фулстек), можешь и на сеньора попробовать пособеседоваться, далеко не везде там жестко требуют, например, в иннотехе у меня собеседования на сеньора в некоторые команды довольно лайтовыми были

2024-12-14 22:10 UTC, jibulani commented on src/test/java/faang/school/analytics/service/implementations/AnalyticsServiceImplTest.java
> +    @Test
рекомендую попробовать сделать этот тест параметризованным для проверки работы с разными интервалами

полезно знать о таких тестах и уметь их писать, потому что на работе часто их пишут

2024-12-15 12:50 UTC, evgen-backend-rostov commented on src/main/java/faang/school/analytics/mapper/GetAnalyticsRqMapper.java
> +                intervalDto = IntervalDto.valueOf(interval.toUpperCase());
я сделал, но не уверен, что правильно тебя понял, потому что кода стало больше 😅

2024-12-15 12:59 UTC, evgen-backend-rostov commented on src/main/java/faang/school/analytics/service/implementations/AnalyticsServiceImpl.java
> +    private Period generatePeriod(IntervalDto intervalDto, LocalDateTime from, LocalDateTime to, Integer count) {
Спасибо за мотивацию! Прям настроение поднял 😊 Просто изо дня в день что-то новое, материал даётся не так легко как хотелось бы, и создаётся ощущение, что на одном месте топчешься...

2024-12-15 13:09 UTC, evgen-backend-rostov commented on src/main/java/faang/school/analytics/service/implementations/AnalyticsServiceImpl.java
> +            switch (intervalDto) {
Круто! Не знал, что switch может значение возвращать. Спасибо)

2024-12-15 13:17 UTC, evgen-backend-rostov commented on src/main/java/faang/school/analytics/service/implementations/AnalyticsServiceImpl.java
> +        return new Period(beginDate, endDate);
по идее, периода может не быть вообще, и тогда нам просто вернутся все записи из базы без ограничений по датам

2024-12-17 21:54 UTC, jibulani requested changes
хорошо!

есть пара моментов для уточнения

2024-12-17 21:54 UTC, jibulani commented on src/main/java/faang/school/analytics/controller/AnalyticsController.java
> +        GetAnalyticsRqDto getAnalyticsRqDto = GetAnalyticsRqMapper.map(paramsDto.receiverId(), paramsDto.eventType(),
что-то не понял, зачем одну дто маппить на другую? почему не передал в аргументах сразу GetAnalyticsRqDto?

2024-12-17 21:54 UTC, jibulani commented on src/test/java/faang/school/analytics/controller/AnalyticsControllerMockMvcTest.java
> +            Thread.sleep(1000);
зачем?

2024-12-17 21:54 UTC, jibulani commented on src/test/java/faang/school/analytics/controller/AnalyticsControllerMockMvcTest.java
> +        assertThat(eventDto.eventType()).isEqualTo(EventTypeDto.POST_LIKE);
круто, что попробовал сделать интеграционный тест!

чтобы он был полноценным, можно еще проверить, что в базе запись нужная появилась

2024-12-17 21:54 UTC, jibulani commented on src/test/java/faang/school/analytics/service/implementations/AnalyticsServiceImplTest.java
> +    public void testGeneratePeriodWithInterval(String interval, int count, int expectedResult) {
супер!

2024-12-18 07:57 UTC, evgen-backend-rostov commented on src/main/java/faang/school/analytics/controller/AnalyticsController.java
> +        GetAnalyticsRqDto getAnalyticsRqDto = GetAnalyticsRqMapper.map(paramsDto.receiverId(), paramsDto.eventType(),
По условиям задачи нужно, чтобы параметры в контроллер прилетали через @RequestParam. Там была большая простыня с параметрами, ты мне скинул статью, как принимать кучу @RequestParam одним объектом. Если я правильно понял, то все эти параметры приходят как String, а мне нужно из них сделать два энама и два значения LocalDateTime, поэтому решил промежуточный маппер сделать.

Если бы не нужно было использовать @RequestParam, я бы сразу нужный объект и передавал бы. Хотя может есть ещё какой-то способ сконвертировать типы?

2024-12-18 08:05 UTC, evgen-backend-rostov commented on src/test/java/faang/school/analytics/controller/AnalyticsControllerMockMvcTest.java
> +            Thread.sleep(1000);
я делал по примеру воркшопа, там объясняли, что это нужно, чтобы типа "все параметры успели прописаться". Прозвучало сомнительно, но проверять я не стал)

2024-12-18 08:07 UTC, evgen-backend-rostov commented on src/test/java/faang/school/analytics/service/implementations/AnalyticsServiceImplTest.java
> +    public void testGeneratePeriodWithInterval(String interval, int count, int expectedResult) {
😊

2024-12-18 10:42 UTC, evgen-backend-rostov commented on src/test/java/faang/school/analytics/controller/AnalyticsControllerMockMvcTest.java
> +            Thread.sleep(1000);
Проверил, работает и без этого 👍

2024-12-18 20:34 UTC, jibulani commented on src/main/java/faang/school/analytics/controller/AnalyticsController.java
> +        GetAnalyticsRqDto getAnalyticsRqDto = GetAnalyticsRqMapper.map(paramsDto.receiverId(), paramsDto.eventType(),
а если GetAnalyticsRqDto в аргументы передать, оно не считает сразу в нужные типы енам и дату?

2024-12-18 20:40 UTC, jibulani approved these changes
есть вопрос, попробуй по-другому, если будет время

если некогда, можешь смержить :)

2024-12-19 18:55 UTC, evgen-backend-rostov commented on src/main/java/faang/school/analytics/controller/AnalyticsController.java
> +        GetAnalyticsRqDto getAnalyticsRqDto = GetAnalyticsRqMapper.map(paramsDto.receiverId(), paramsDto.eventType(),
Проверил, так тоже работает, но есть нюансы:
1. Если параметры для enum передавать в lowerCase, то вылетает ошибка валидации. Сейчас думаю, что может, если для enum задать значения в lowerCase, то ошибка уйдёт?
2. И пришлось со Spring validation поколдовать: аннотации @Valid в сигнатуре метода контроллера оказалось недостаточно. Повесил ещё @Validated на сам дто класс, и всё заработало. Хотя на самом классе контроллера @Validated тоже висит

2024-12-19 18:56 UTC, merged