Feature/bjs2-41432
CorporationX/analytics_service pull request #346
Opened 2024-12-13 17:08 UTC by DaniyarDostiev

Анализ просмотров постов

2024-12-15 09:47 UTC, frs717 commented on src/main/java/faang/school/analytics/config/redis/RedisConfig.java
> +    @Value("${${spring.data.redis.channel.recommendation_topic}")
А тут так и должно быть ? - `${${`

2024-12-16 10:53 UTC, DaniyarDostiev commented on src/main/java/faang/school/analytics/config/redis/RedisConfig.java
> +    @Value("${${spring.data.redis.channel.recommendation_topic}")
нет)
уже поправил.

2024-12-25 13:57 UTC, MiraGlaceon requested changes

2024-12-25 13:57 UTC, MiraGlaceon commented on src/main/java/faang/school/analytics/controller/events/AnalyticsEventController.java
> +    @PostMapping("/save-event")
Было правильно все. Лучше оставь как рекомендуют лучшие практики /analytics/events, а с экшенами сделай /analytics/actions. Это же тоже самое

2024-12-25 13:57 UTC, MiraGlaceon commented on src/main/java/faang/school/analytics/service/events/AnalyticsEventService.java
> +        return analyticsEventMapper.toDto(analyticsEventRepository.save(event));
У тебя уже есть analyticsEventDto, не нужно два раза преобразовывать

2024-12-26 10:11 UTC, nue-01 commented on src/main/java/faang/school/analytics/service/events/AnalyticsEventService.java
> +        return analyticsEventMapper.toDto(analyticsEventRepository.save(event));
При первом преобразовании в entity не хватает поля id всей записи, я его получаю после выполнения save.

2025-01-08 15:04 UTC, MiraGlaceon approved these changes

2025-01-09 09:36 UTC, merged