Feature/bjs2 41435
CorporationX/analytics_service pull request #364
Opened 2024-12-21 13:00 UTC by frs717

2024-12-25 14:31 UTC, MiraGlaceon requested changes

2024-12-25 14:31 UTC, MiraGlaceon commented on src/main/java/faang/school/analytics/config/redis/RedisConfig.java
> +//        result.put(GoalCompletedEventListener.class.getName(), new ChannelTopic(goalCompletedChannel));
Если не нужен, то удали. Плохая привычка сохранять комментированный код на потом. Чаще всего он никогда не пригодиться и будет просто существовать в коде вечно. А если что-то уж надо потом доделать, то лучше оставлять // todo или // fixme

2024-12-29 15:27 UTC, frs717 commented on src/main/java/faang/school/analytics/config/redis/RedisConfig.java
> +//        result.put(GoalCompletedEventListener.class.getName(), new ChannelTopic(goalCompletedChannel));
Исправлено

2025-01-08 15:37 UTC, MiraGlaceon approved these changes

2025-01-08 15:59 UTC, merged