Собирает информацию в момент, когда пользователь комментит пост друго…
CorporationX/analytics_service pull request #368
Opened 2024-12-22 11:38 UTC by StanislawKO

…го пользователя и сохраняет информацию из этих событий с БД, используя AnalyticsEventService

2024-12-22 13:55 UTC, evgen-backend-rostov commented on src/main/java/faang/school/analytics/dto/AnalyticsEventMapper.java
может вынести этот файл в отдельную папку mapper?

2024-12-22 13:59 UTC, evgen-backend-rostov commented on src/main/java/faang/school/analytics/dto/Event.java
скажи пожалуйста, для чего сделан этот интерфейс? Я понимаю, что ты его используешь как маркер, но не пойму, какую на этом логику можно накрутить?

2024-12-22 19:33 UTC, StanislawKO commented on src/main/java/faang/school/analytics/dto/AnalyticsEventMapper.java
задумка была следующая - у нас есть сервис аналитики, который слушает другие сервисы, они передают информацию в виде ивентов, соответственно все эти ивенты собираем воедино и можем прогонять на них общую логику

2024-12-22 20:01 UTC, StanislawKO commented on src/main/java/faang/school/analytics/dto/Event.java
задумка была следующая - у нас есть сервис аналитики, который слушает другие сервисы, они передают информацию в виде ивентов, соответственно, все эти ивенты собираем воедино и можем прогонять на них общую логику. Например, если делаем коммент, то автор коммента хотел бы получить уведомление о том, что его пост откомментировали или кто то поставил лайк, тоже был бы неплохо получить уведомление, поэтому CommentEvent и LikeEvent объединяем общим интерфейсом, если у нас слушатель событий тоже проходим по ивентам чтобы выяснить топ 10 самых популярных и показать их на главной странице или присвоить им какой нибудь супер статус.

2024-12-23 16:09 UTC, evgen-backend-rostov commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +    public AnalyticsEvent addAnalyticsEvent(AnalyticsEvent analyticsEvent) {
в корневой ветке Centaur-master-stream7 уже залит метод сервиса для сохранения события аналитики. Подтяни себе изменения, там будет немного конфликтов

2024-12-23 19:01 UTC, StanislawKO commented on src/main/java/faang/school/analytics/service/AnalyticsEventService.java
> +    public AnalyticsEvent addAnalyticsEvent(AnalyticsEvent analyticsEvent) {
хорошо, спасибо

2025-01-21 17:42 UTC, jibulani requested changes
хорошо, оставил пару комментариев

2025-01-21 17:42 UTC, jibulani commented on src/main/java/faang/school/analytics/config/redis/RedisConfiguration.java
> +        container.addMessageListener(commentListener, commentTopic());
зачем делаешь вызов commentTopic()? просто передай его в аргументах

2025-01-21 17:42 UTC, jibulani commented on src/main/java/faang/school/analytics/listeners/CommentEventListener.java
> +    public void onMessage(Message message, byte[] pattern) {
нужны тесты на этот метод

2025-01-22 22:09 UTC, jibulani approved these changes
хорошо!

2025-01-22 22:09 UTC, merged