Murloc amanyaz stream7 analytics service bjs2 41471
CorporationX/analytics_service pull request #372
Opened 2024-12-25 18:07 UTC by Amanyaz

2024-12-26 01:25 UTC, alexFromAC143937 commented on src/main/java/faang/school/analytics/config/context/redis/RedisConfiguration.java
> +public class RedisConfiguration {
Есть в репозитории RedisConfiguration, Руслан 23/12 залил и он отличается от написанного здесь

2024-12-26 01:25 UTC, alexFromAC143937 commented on src/main/java/faang/school/analytics/config/context/redis/RedisProperties.java
> +    protected static class Channels {
Есть класс написанный Русланом и ест оличия в подходе написания, посомтри, пожалуйста.

2024-12-26 01:25 UTC, alexFromAC143937 commented on src/main/java/faang/school/analytics/listener/PostViewEventListener.java
> +        } catch (IOException e) {
Предлагаю написать логирование

2024-12-26 17:19 UTC, Amanyaz commented on src/main/java/faang/school/analytics/config/context/redis/RedisConfiguration.java
> +public class RedisConfiguration {
Готово! Я начал до того, как Руслан слил изменения, поэтому это произошло. Сейчас я удалил свои файлы RedisConfig и RedisProperties и добавил свою конфигурацию в файл Руслана.

2024-12-26 17:19 UTC, Amanyaz commented on src/main/java/faang/school/analytics/config/context/redis/RedisProperties.java
> +    protected static class Channels {
Готово! Я начал до того, как Руслан слил изменения, поэтому это произошло. Сейчас я удалил свои файлы RedisConfig и RedisProperties и добавил свою конфигурацию в файл Руслана.

2024-12-26 17:19 UTC, Amanyaz commented on src/main/java/faang/school/analytics/listener/PostViewEventListener.java
> +        } catch (IOException e) {
Логирование уже реализовано в абстрактном классе AbstractEventListener Руслана. Я унаследовал этот абстрактный класс.

2024-12-27 04:12 UTC, alexFromAC143937 approved these changes

2024-12-29 12:40 UTC, jibulani requested changes
хорошо, молодец!

есть пара небольших моментов для исправления

2024-12-29 12:40 UTC, jibulani commented on src/main/java/faang/school/analytics/model/dto/AnalyticsEventDto.java
> +        java.time.LocalDateTime receivedAt
зачем?

2024-12-29 12:40 UTC, jibulani commented on src/test/java/faang/school/analytics/mapper/AnalyticsEventMapperTest.java
> +    void testToEntityFromPPostViewEvent_NullSource() {
PPost -> Post надо поправить

2024-12-29 14:24 UTC, Amanyaz commented on src/test/java/faang/school/analytics/mapper/AnalyticsEventMapperTest.java
> +    void testToEntityFromPPostViewEvent_NullSource() {
Готово!

2024-12-29 14:26 UTC, Amanyaz commented on src/main/java/faang/school/analytics/model/dto/AnalyticsEventDto.java
> +        java.time.LocalDateTime receivedAt
Готово!

2024-12-29 21:27 UTC, jibulani approved these changes
супер!

2024-12-29 21:28 UTC, merged