Complete task BJS2-2186 in analytics service
CorporationX/analytics_service pull request #76
Opened 2024-03-04 10:02 UTC by asbulgakov

2024-03-04 15:09 UTC, Edisolt5498 requested changes

2024-03-04 15:09 UTC, Edisolt5498 commented on src/main/java/faang/school/analytics/config/redis/RedisConfig.java
> +        return new ChannelTopic("SearchAppearanceEvent");
конфиг

2024-03-04 15:09 UTC, Edisolt5498 commented on src/main/java/faang/school/analytics/service/RedisMessageSubscriber.java
> +    private static final Logger logger =
@Slf4j эта аннотация разве не для логов?

2024-03-04 16:12 UTC, asbulgakov commented on src/main/java/faang/school/analytics/config/redis/RedisConfig.java
> +        return new ChannelTopic("SearchAppearanceEvent");
вынес)

2024-03-04 16:12 UTC, asbulgakov commented on src/main/java/faang/school/analytics/service/RedisMessageSubscriber.java
> +    private static final Logger logger =
да, ты прав, поле можно не использовать)

2024-03-10 14:38 UTC, InnMish commented on src/main/java/faang/school/analytics/config/redis/RedisConfig.java
> +        System.out.println(port);
это удаляем

2024-03-10 14:38 UTC, InnMish commented on src/main/java/faang/school/analytics/config/redis/RedisConfig.java
> +    private ObjectMapper objectMapper;
сюда их не надо, мы руками не конфигурируем бины здесь

2024-03-10 14:38 UTC, InnMish commented on src/main/java/faang/school/analytics/config/redis/RedisConfig.java
> +                                            MessageListenerAdapter messageListenerAdapter) {
в него не нужно передавать фактори - ты уже настроил коннект на 50 строчке

2024-03-10 14:38 UTC, InnMish commented on src/main/java/faang/school/analytics/config/redis/RedisConfig.java
> +        container.setConnectionFactory(connectionFactory);
то есть сюда прям бин redisConnectionFactory клади, он тут же, его параметром передавать не надо

2024-03-10 14:38 UTC, InnMish commented on src/main/java/faang/school/analytics/config/redis/RedisConfig.java
> +    }
SearchAppearanceEventListener  тут не конфигурируем. Просто его испортируешь в этот файл конфигурации бином именно отдельным - он где-то в другом месте будет создаваться) 
А тут ты используешь его уже готовым. 

Здесь у тебя будет примерно так: return new MessageListenerAdapter(searchAppearanceEventListener );

2024-03-10 14:38 UTC, InnMish commented on src/main/java/faang/school/analytics/config/redis/RedisConfig.java
> +    ChannelTopic topic() {
назови сразу понятным названием именно для твоего события: searchAppearanceChannel

2024-03-10 14:38 UTC, InnMish commented on src/main/java/faang/school/analytics/listener/SearchAppearanceEventListener.java
> +public class SearchAppearanceEventListener implements MessageListener {
Сейчас этот лисенер работает только для твоего события 
А когда кто-то другой будет новое событие отправлять, ему придется писать точно такой же onMessage метод в своем классе 

Давай сделаем абстрактный класс, в котором будет собрана общая логика - например, с обджект маппером 
А все остальное уже будет делать в классах наследниках

2024-03-10 14:38 UTC, InnMish commented on src/main/java/faang/school/analytics/listener/SearchAppearanceEventListener.java
> +            analyticsEventService.save(analyticsEvent);
вот это должно быть а наследнике, а все остальное здесь

2024-03-20 07:46 UTC, InnMish commented on src/main/resources/application.yaml
> +    name: SearchAppearanceChannel
на 24 строчке есть вон названия каналов) 
Давай писать везде одинаково, тут уже создан конфиг для редиса

2024-03-20 07:46 UTC, InnMish commented on src/main/java/faang/school/analytics/event/SearchAppearanceEvent.java
> +public record SearchAppearanceEvent(
это же дто у тебя, которые ты получаешь из редиса

2024-03-20 07:46 UTC, InnMish commented on src/main/java/faang/school/analytics/listener/SearchAppearanceEventListener.java
> +        analyticsEventService.save(analyticsEvent);
А у тебя где-то проставляется тип события перед сохранением? Не нашла

2024-03-21 08:36 UTC, InnMish commented on src/main/java/faang/school/analytics/config/RedisConfig.java
> +
а разве это работает?) Если ты в редис контейнер лисенер не добавил

2024-03-21 08:36 UTC, InnMish commented on src/main/java/faang/school/analytics/listener/SearchAppearanceEventListener.java
> +    public SearchAppearanceEventListener(Class<SearchAppearanceEventDto> type, AnalyticsEventService analyticsEventService, AnalyticsEventMapper analyticsEventMapper) {
eventService и маппер можно не передавать, они в абстрактном классе и так инжектятся же)

2024-03-24 08:02 UTC, merged